root: true
parser: "@typescript-eslint/parser"
plugins: ["@typescript-eslint"]
extends: ["eslint:recommended", "plugin:@typescript-eslint/recommended"]
rules:
  semi: [2, "always"]
  "@typescript-eslint/no-unused-vars": "error"
  "@typescript-eslint/no-explicit-any": 0
  "@typescript-eslint/explicit-module-boundary-types": 0
  "@typescript-eslint/no-non-null-assertion": 0
  "@typescript-eslint/no-namespace": 0
  quotes:
    - "error"
    - "double"
  no-duplicate-imports: "error"
