interface BuiltinEncode {
  name: string;
  args: string[];
  doc: string;
}

export const builtinEncode: BuiltinEncode[] = [
  {
    name: "$L",
    args: ["t"],
    doc: "Encode Location Name",
  },
  {
    name: "$U",
    args: ["t"],
    doc: "Encode Unit Name",
  },
  {
    name: "$T",
    args: ["t"],
    doc: "Encode Map String",
  },
  {
    name: "$B",
    args: ["t"],
    doc: "Encode stat_txt.tbl",
  },
  {
    name: "$S",
    args: ["t"],
    doc: "Encode Switch Name",
  },
];

export type SCTrgEncode =
  | "TrgAllyStatus"
  | "TrgProperty"
  | "TrgSwitchState"
  | "TrgSwitchAction"
  | "TrgComparison"
  | "TrgModifier"
  | "TrgOrder"
  | "TrgPlayer"
  | "TrgProperty"
  | "TrgResource"
  | "TrgScore"
  | "TrgAIScript"
  | "TrgUnit"
  | "TrgTBL"
  | "Image"
  | "Iscript";

export const SCTrgAllyStatus = [];
export const SCTrgPropState = ["Enable", "Disable", "Toggle"];
export const SCTrgSwitchState = ["Set", "Cleared"];
export const SCTrgSwitchAction = ["Set", "Clear", "Toggle", "Random"];

export const SCTrgComparison = ["AtLeast", "AtMost", "Exactly"];

export const SCTrgModifier = ["Add", "SetTo", "Subtract"];

export const SCTrgOrder = ["Attack", "Patrol", "Move"];

export const SCTrgPlayer = [
  "P1",
  "P2",
  "P3",
  "P4",
  "P5",
  "P6",
  "P7",
  "P8",
  "P9",
  "P10",
  "P11",
  "P12",
  "CurrentPlayer",
  "Foes",
  "Allies",
  "NeutralPlayers",
  "Force1",
  "Force2",
  "Force3",
  "Force4",
  "NonAlliesVictoryPlayers",
];

export const SCTrgProperty = [];

export const SCTrgResource = ["Ore", "Gas", "OreAndGas"];

export const SCTrgScore = [
  "Units",
  "Buildings",
  "UnitsAndBuildings",
  "Kills",
  "Razings",
  "KillsAndRazings",
  "Custom",
];

export const SCTrgAIScript = [
  "Terran Custom Level",
  "Zerg Custom Level",
  "Protoss Custom Level",
  "Terran Expansion Custom Level",
  "Zerg Expansion Custom Level",
  "Protoss Expansion Custom Level",
  "Terran Campaign Easy",
  "Terran Campaign Medium",
  "Terran Campaign Difficult",
  "Terran Campaign Insane",
  "Terran Campaign Area Town",
  "Zerg Campaign Easy",
  "Zerg Campaign Medium",
  "Zerg Campaign Difficult",
  "Zerg Campaign Insane",
  "Zerg Campaign Area Town",
  "Protoss Campaign Easy",
  "Protoss Campaign Medium",
  "Protoss Campaign Difficult",
  "Protoss Campaign Insane",
  "Protoss Campaign Area Town",
  "Expansion Terran Campaign Easy",
  "Expansion Terran Campaign Medium",
  "Expansion Terran Campaign Difficult",
  "Expansion Terran Campaign Insane",
  "Expansion Terran Campaign Area Town",
  "Expansion Zerg Campaign Easy",
  "Expansion Zerg Campaign Medium",
  "Expansion Zerg Campaign Difficult",
  "Expansion Zerg Campaign Insane",
  "Expansion Zerg Campaign Area Town",
  "Expansion Protoss Campaign Easy",
  "Expansion Protoss Campaign Medium",
  "Expansion Protoss Campaign Difficult",
  "Expansion Protoss Campaign Insane",
  "Expansion Protoss Campaign Area Town",
  "Send All Units on Strategic Suicide Missions",
  "Send All Units on Random Suicide Missions",
  "Switch Computer Player to Rescue Passive",
  "Turn ON Shared Vision for Player 1",
  "Turn ON Shared Vision for Player 2",
  "Turn ON Shared Vision for Player 3",
  "Turn ON Shared Vision for Player 4",
  "Turn ON Shared Vision for Player 5",
  "Turn ON Shared Vision for Player 6",
  "Turn ON Shared Vision for Player 7",
  "Turn ON Shared Vision for Player 8",
  "Turn OFF Shared Vision for Player 1",
  "Turn OFF Shared Vision for Player 2",
  "Turn OFF Shared Vision for Player 3",
  "Turn OFF Shared Vision for Player 4",
  "Turn OFF Shared Vision for Player 5",
  "Turn OFF Shared Vision for Player 6",
  "Turn OFF Shared Vision for Player 7",
  "Turn OFF Shared Vision for Player 8",
  "Move Dark Templars to Region",
  "Clear Previous Combat Data",
  "Set Player to Enemy",
  "Set Player to Ally  ",
  "Value This Area Higher",
  "Enter Closest Bunker",
  "Set Generic Command Target",
  "Make These Units Patrol",
  "Enter Transport",
  "Exit Transport",
  "AI Nuke Here",
  "AI Harass Here",
  "Set Unit Order To: Junk Yard Dog",
  "Disruption Web Here",
  "Recall Here",
  "Terran 3 - Zerg Town",
  "Terran 5 - Terran Main Town",
  "Terran 5 - Terran Harvest Town",
  "Terran 6 - Air Attack Zerg",
  "Terran 6 - Ground Attack Zerg",
  "Terran 6 - Zerg Support Town",
  "Terran 7 - Bottom Zerg Town",
  "Terran 7 - Right Zerg Town",
  "Terran 7 - Middle Zerg Town",
  "Terran 8 - Confederate Town",
  "Terran 9 - Light Attack",
  "Terran 9 - Heavy Attack",
  "Terran 10 - Confederate Towns",
  "Terran 11 - Zerg Town",
  "Terran 11 - Lower Protoss Town",
  "Terran 11 - Upper Protoss Town",
  "Terran 12 - Nuke Town",
  "Terran 12 - Phoenix Town",
  "Terran 12 - Tank Town",
  "Terran 1 - Electronic Distribution",
  "Terran 2 - Electronic Distribution",
  "Terran 3 - Electronic Distribution",
  "Terran 1 - Shareware",
  "Terran 2 - Shareware",
  "Terran 3 - Shareware",
  "Terran 4 - Shareware",
  "Terran 5 - Shareware",
  "Zerg 1 - Terran Town",
  "Zerg 2 - Protoss Town",
  "Zerg 3 - Terran Town",
  "Zerg 4 - Right Terran Town",
  "Zerg 4 - Lower Terran Town",
  "Zerg 6 - Protoss Town",
  "Zerg 7 - Air Town",
  "Zerg 7 - Ground Town",
  "Zerg 7 - Support Town",
  "Zerg 8 - Scout Town",
  "Zerg 8 - Templar Town",
  "Zerg 9 - Teal Protoss",
  "Zerg 9 - Left Yellow Protoss",
  "Zerg 9 - Right Yellow Protoss",
  "Zerg 9 - Left Orange Protoss",
  "Zerg 9 - Right Orange Protoss",
  "Zerg 10 - Left Teal (Attack",
  "Zerg 10 - Right Teal (Support",
  "Zerg 10 - Left Yellow (Support",
  "Zerg 10 - Right Yellow (Attack",
  "Zerg 10 - Red Protoss",
  "Protoss 1 - Zerg Town",
  "Protoss 2 - Zerg Town",
  "Protoss 3 - Air Zerg Town",
  "Protoss 3 - Ground Zerg Town",
  "Protoss 4 - Zerg Town",
  "Protoss 5 - Zerg Town Island",
  "Protoss 5 - Zerg Town Base",
  "Protoss 7 - Left Protoss Town",
  "Protoss 7 - Right Protoss Town",
  "Protoss 7 - Shrine Protoss",
  "Protoss 8 - Left Protoss Town",
  "Protoss 8 - Right Protoss Town",
  "Protoss 8 - Protoss Defenders",
  "Protoss 9 - Ground Zerg",
  "Protoss 9 - Air Zerg",
  "Protoss 9 - Spell Zerg",
  "Protoss 10 - Mini-Towns",
  "Protoss 10 - Mini-Town Master",
  "Protoss 10 - Overmind Defenders",
  "Brood Wars Protoss 1 - Town A",
  "Brood Wars Protoss 1 - Town ",
  "Brood Wars Protoss 1 - Town C",
  "Brood Wars Protoss 1 - Town D",
  "Brood Wars Protoss 1 - Town E",
  "Brood Wars Protoss 1 - Town F",
  "Brood Wars Protoss 2 - Town A",
  "Brood Wars Protoss 2 - Town ",
  "Brood Wars Protoss 2 - Town C",
  "Brood Wars Protoss 2 - Town D",
  "Brood Wars Protoss 2 - Town E",
  "Brood Wars Protoss 2 - Town F",
  "Brood Wars Protoss 3 - Town A",
  "Brood Wars Protoss 3 - Town ",
  "Brood Wars Protoss 3 - Town C",
  "Brood Wars Protoss 3 - Town D",
  "Brood Wars Protoss 3 - Town E",
  "Brood Wars Protoss 3 - Town F",
  "Brood Wars Protoss 4 - Town A",
  "Brood Wars Protoss 4 - Town ",
  "Brood Wars Protoss 4 - Town C",
  "Brood Wars Protoss 4 - Town D",
  "Brood Wars Protoss 4 - Town E",
  "Brood Wars Protoss 4 - Town F",
  "Brood Wars Protoss 5 - Town A",
  "Brood Wars Protoss 5 - Town ",
  "Brood Wars Protoss 5 - Town C",
  "Brood Wars Protoss 5 - Town D",
  "Brood Wars Protoss 5 - Town E",
  "Brood Wars Protoss 5 - Town F",
  "Brood Wars Protoss 6 - Town A",
  "Brood Wars Protoss 6 - Town ",
  "Brood Wars Protoss 6 - Town C",
  "Brood Wars Protoss 6 - Town D",
  "Brood Wars Protoss 6 - Town E",
  "Brood Wars Protoss 6 - Town F",
  "Brood Wars Protoss 7 - Town A",
  "Brood Wars Protoss 7 - Town ",
  "Brood Wars Protoss 7 - Town C",
  "Brood Wars Protoss 7 - Town D",
  "Brood Wars Protoss 7 - Town E",
  "Brood Wars Protoss 7 - Town F",
  "Brood Wars Protoss 8 - Town A",
  "Brood Wars Protoss 8 - Town ",
  "Brood Wars Protoss 8 - Town C",
  "Brood Wars Protoss 8 - Town D",
  "Brood Wars Protoss 8 - Town E",
  "Brood Wars Protoss 8 - Town F",
  "Brood Wars Terran 1 - Town A",
  "Brood Wars Terran 1 - Town ",
  "Brood Wars Terran 1 - Town C",
  "Brood Wars Terran 1 - Town D",
  "Brood Wars Terran 1 - Town E",
  "Brood Wars Terran 1 - Town F",
  "Brood Wars Terran 2 - Town A",
  "Brood Wars Terran 2 - Town ",
  "Brood Wars Terran 2 - Town C",
  "Brood Wars Terran 2 - Town D",
  "Brood Wars Terran 2 - Town E",
  "Brood Wars Terran 2 - Town F",
  "Brood Wars Terran 3 - Town A",
  "Brood Wars Terran 3 - Town ",
  "Brood Wars Terran 3 - Town C",
  "Brood Wars Terran 3 - Town D",
  "Brood Wars Terran 3 - Town E",
  "Brood Wars Terran 3 - Town F",
  "Brood Wars Terran 4 - Town A",
  "Brood Wars Terran 4 - Town ",
  "Brood Wars Terran 4 - Town C",
  "Brood Wars Terran 4 - Town D",
  "Brood Wars Terran 4 - Town E",
  "Brood Wars Terran 4 - Town F",
  "Brood Wars Terran 5 - Town A",
  "Brood Wars Terran 5 - Town ",
  "Brood Wars Terran 5 - Town C",
  "Brood Wars Terran 5 - Town D",
  "Brood Wars Terran 5 - Town E",
  "Brood Wars Terran 5 - Town F",
  "Brood Wars Terran 6 - Town A",
  "Brood Wars Terran 6 - Town ",
  "Brood Wars Terran 6 - Town C",
  "Brood Wars Terran 6 - Town D",
  "Brood Wars Terran 6 - Town E",
  "Brood Wars Terran 6 - Town F",
  "Brood Wars Terran 7 - Town A",
  "Brood Wars Terran 7 - Town ",
  "Brood Wars Terran 7 - Town C",
  "Brood Wars Terran 7 - Town D",
  "Brood Wars Terran 7 - Town E",
  "Brood Wars Terran 7 - Town F",
  "Brood Wars Terran 8 - Town A",
  "Brood Wars Terran 8 - Town ",
  "Brood Wars Terran 8 - Town C",
  "Brood Wars Terran 8 - Town D",
  "Brood Wars Terran 8 - Town E",
  "Brood Wars Terran 8 - Town F",
  "Brood Wars Zerg 1 - Town A",
  "Brood Wars Zerg 1 - Town ",
  "Brood Wars Zerg 1 - Town C",
  "Brood Wars Zerg 1 - Town D",
  "Brood Wars Zerg 1 - Town E",
  "Brood Wars Zerg 1 - Town F",
  "Brood Wars Zerg 2 - Town A",
  "Brood Wars Zerg 2 - Town ",
  "Brood Wars Zerg 2 - Town C",
  "Brood Wars Zerg 2 - Town D",
  "Brood Wars Zerg 2 - Town E",
  "Brood Wars Zerg 2 - Town F",
  "Brood Wars Zerg 3 - Town A",
  "Brood Wars Zerg 3 - Town ",
  "Brood Wars Zerg 3 - Town C",
  "Brood Wars Zerg 3 - Town D",
  "Brood Wars Zerg 3 - Town E",
  "Brood Wars Zerg 3 - Town F",
  "Brood Wars Zerg 4 - Town A",
  "Brood Wars Zerg 4 - Town ",
  "Brood Wars Zerg 4 - Town C",
  "Brood Wars Zerg 4 - Town D",
  "Brood Wars Zerg 4 - Town E",
  "Brood Wars Zerg 4 - Town F",
  "Brood Wars Zerg 5 - Town A",
  "Brood Wars Zerg 5 - Town ",
  "Brood Wars Zerg 5 - Town C",
  "Brood Wars Zerg 5 - Town D",
  "Brood Wars Zerg 5 - Town E",
  "Brood Wars Zerg 5 - Town F",
  "Brood Wars Zerg 6 - Town A",
  "Brood Wars Zerg 6 - Town ",
  "Brood Wars Zerg 6 - Town C",
  "Brood Wars Zerg 6 - Town D",
  "Brood Wars Zerg 6 - Town E",
  "Brood Wars Zerg 6 - Town F",
  "Brood Wars Zerg 7 - Town A",
  "Brood Wars Zerg 7 - Town ",
  "Brood Wars Zerg 7 - Town C",
  "Brood Wars Zerg 7 - Town D",
  "Brood Wars Zerg 7 - Town E",
  "Brood Wars Zerg 7 - Town F",
  "Brood Wars Zerg 8 - Town A",
  "Brood Wars Zerg 8 - Town ",
  "Brood Wars Zerg 8 - Town C",
  "Brood Wars Zerg 8 - Town D",
  "Brood Wars Zerg 8 - Town E",
  "Brood Wars Zerg 8 - Town F",
  "Brood Wars Zerg 9 - Town A",
  "Brood Wars Zerg 9 - Town ",
  "Brood Wars Zerg 9 - Town C",
  "Brood Wars Zerg 9 - Town D",
  "Brood Wars Zerg 9 - Town E",
  "Brood Wars Zerg 9 - Town F",
  "Brood Wars Zerg 10 - Town A",
  "Brood Wars Zerg 10 - Town ",
  "Brood Wars Zerg 10 - Town C",
  "Brood Wars Zerg 10 - Town D",
  "Brood Wars Zerg 10 - Town E",
  "Brood Wars Zerg 10 - Town F",
];

export const SCTrgUnit = [
  "Terran Marine",
  "Terran Ghost",
  "Terran Vulture",
  "Terran Goliath",
  "Goliath Turret",
  "Terran Siege Tank (Tank Mode)",
  "Tank Turret",
  "Terran SCV",
  "Terran Wraith",
  "Terran Science Vessel",
  "Gui Montag (Firebat)",
  "Terran Dropship",
  "Terran Battlecruiser",
  "Vulture Spider Mine",
  "Nuclear Missile",
  "Terran Civilian",
  "Sarah Kerrigan (Ghost)",
  "Alan Schezar (Goliath)",
  "Alan Turret",
  "Jim Raynor (Vulture)",
  "Jim Raynor (Marine)",
  "Tom Kazansky (Wraith)",
  "Magellan (Science Vessel)",
  "Edmund Duke (Siege Tank)",
  "Duke Turret",
  "Edmund Duke (Siege Mode)",
  "Duke Turret",
  "Arcturus Mengsk (Battlecruiser)",
  "Hyperion (Battlecruiser)",
  "Norad II (Battlecruiser)",
  "Terran Siege Tank (Siege Mode)",
  "Tank Turret",
  "Terran Firebat",
  "Scanner Sweep",
  "Terran Medic",
  "Zerg Larva",
  "Zerg Egg",
  "Zerg Zergling",
  "Zerg Hydralisk",
  "Zerg Ultralisk",
  "Zerg Broodling",
  "Zerg Drone",
  "Zerg Overlord",
  "Zerg Mutalisk",
  "Zerg Guardian",
  "Zerg Queen",
  "Zerg Defiler",
  "Zerg Scourge",
  "Torrasque (Ultralisk)",
  "Matriarch (Queen)",
  "Infested Terran",
  "Infested Kerrigan (Infested Terran)",
  "Unclean One (Defiler)",
  "Hunter Killer (Hydralisk)",
  "Devouring One (Zergling)",
  "Kukulza (Mutalisk)",
  "Kukulza (Guardian)",
  "Yggdrasill (Overlord)",
  "Terran Valkyrie",
  "Cocoon",
  "Protoss Corsair",
  "Protoss Dark Templar",
  "Zerg Devourer",
  "Protoss Dark Archon",
  "Protoss Probe",
  "Protoss Zealot",
  "Protoss Dragoon",
  "Protoss High Templar",
  "Protoss Archon",
  "Protoss Shuttle",
  "Protoss Scout",
  "Protoss Arbiter",
  "Protoss Carrier",
  "Protoss Interceptor",
  "Dark Templar (Hero)",
  "Zeratul (Dark Templar)",
  "Tassadar/Zeratul (Archon)",
  "Fenix (Zealot)",
  "Fenix (Dragoon)",
  "Tassadar (Templar)",
  "Mojo (Scout)",
  "Warbringer (Reaver)",
  "Gantrithor (Carrier)",
  "Protoss Reaver",
  "Protoss Observer",
  "Protoss Scarab",
  "Danimoth (Arbiter)",
  "Aldaris (Templar)",
  "Artanis (Scout)",
  "Rhynadon (Badlands)",
  "Bengalaas (Jungle)",
  "Unused",
  "Unused",
  "Scantid (Desert)",
  "Kakaru (Twilight)",
  "Ragnasaur (Ash World)",
  "Ursadon (Ice World)",
  "Zerg Lurker Egg",
  "Raszagal (Dark Templar)",
  "Samir Duran (Ghost)",
  "Alexei Stukov (Ghost)",
  "Map Revealer",
  "Gerard DuGalle (Ghost)",
  "Zerg Lurker",
  "Infested Duran",
  "Disruption Field",
  "Terran Command Center",
  "Terran Comsat Station",
  "Terran Nuclear Silo",
  "Terran Supply Depot",
  "Terran Refinery",
  "Terran Barracks",
  "Terran Academy",
  "Terran Factory",
  "Terran Starport",
  "Terran Control Tower",
  "Terran Science Facility",
  "Terran Covert Ops",
  "Terran Physics Lab",
  "Unused Terran Bldg",
  "Terran Machine Shop",
  "Unused Terran Bldg",
  "Terran Engineering Bay",
  "Terran Armory",
  "Terran Missile Turret",
  "Terran Bunker",
  "Norad II (Crashed Battlecruiser)",
  "Ion Cannon",
  "Uraj Crystal",
  "Khalis Crystal",
  "Infested Command Center",
  "Zerg Hatchery",
  "Zerg Lair",
  "Zerg Hive",
  "Zerg Nydus Canal",
  "Zerg Hydralisk Den",
  "Zerg Defiler Mound",
  "Zerg Greater Spire",
  "Zerg Queen's Nest",
  "Zerg Evolution Chamber",
  "Zerg Ultralisk Cavern",
  "Zerg Spire",
  "Zerg Spawning Pool",
  "Zerg Creep Colony",
  "Zerg Spore Colony",
  "Unused Zerg Bldg",
  "Zerg Sunken Colony",
  "Zerg Overmind (With Shell)",
  "Zerg Overmind",
  "Zerg Extractor",
  "Mature Crysalis",
  "Zerg Cerebrate",
  "Zerg Cerebrate Daggoth",
  "Unused Zerg Bldg 5",
  "Protoss Nexus",
  "Protoss Robotics Facility",
  "Protoss Pylon",
  "Protoss Assimilator",
  "Protoss Unused",
  "Protoss Observatory",
  "Protoss Gateway",
  "Protoss Unused",
  "Protoss Photon Cannon",
  "Protoss Citadel of Adun",
  "Protoss Cybernetics Core",
  "Protoss Templar Archives",
  "Protoss Forge",
  "Protoss Stargate",
  "Stasis Cell/Prison",
  "Protoss Fleet Beacon",
  "Protoss Arbiter Tribunal",
  "Protoss Robotics Support Bay",
  "Protoss Shield Battery",
  "Khaydarin Crystal Formation",
  "Protoss Temple",
  "Xel'Naga Temple",
  "Mineral Field (Type 1)",
  "Mineral Field (Type 2)",
  "Mineral Field (Type 3)",
  "Cave",
  "Cave-in",
  "Cantina",
  "Mining Platform",
  "Independent Command Center",
  "Independent Starport",
  "Jump Gate",
  "Ruins",
  "Kyadarin Crystal Formation",
  "Vespene Geyser",
  "Warp Gate",
  "Psi Disrupter",
  "Zerg Marker",
  "Terran Marker",
  "Protoss Marker",
  "Zerg Beacon",
  "Terran Beacon",
  "Protoss Beacon",
  "Zerg Flag Beacon",
  "Terran Flag Beacon",
  "Protoss Flag Beacon",
  "Power Generator",
  "Overmind Cocoon",
  "Dark Swarm",
  "Floor Missile Trap",
  "Floor Hatch (UNUSED)",
  "Left Upper Level Door",
  "Right Upper Level Door",
  "Left Pit Door",
  "Right Pit Door",
  "Floor Gun Trap",
  "Left Wall Missile Trap",
  "Left Wall Flame Trap",
  "Right Wall Missile Trap",
  "Right Wall Flame Trap",
  "Start Location",
  "Flag",
  "Young Chrysalis",
  "Psi Emitter",
  "Data Disc",
  "Khaydarin Crystal",
  "Mineral Chunk (Type 1)",
  "Mineral Chunk (Type 2)",
  "Vespene Orb (Protoss Type 1)",
  "Vespene Orb (Protoss Type 2)",
  "Vespene Sac (Zerg Type 1)",
  "Vespene Sac (Zerg Type 2)",
  "Vespene Tank (Terran Type 1)",
  "Vespene Tank (Terran Type 2)",
];

export const SCTrgTBL = [
  "Terran Marine",
  "Terran Ghost",
  "Terran Vulture",
  "Terran Goliath",
  "Goliath Turret",
  "Terran Siege Tank (Tank Mode)",
  "Siege Tank Turret (Tank Mode)",
  "Tank Turret type   1",
  "Terran SCV",
  "Terran Wraith",
  "Terran Science Vessel",
  "Gui Montag",
  "Gui Montag (Firebat)",
  "Terran Dropship",
  "Terran Battlecruiser",
  "Spider Mine",
  "Vulture Spider Mine",
  "Nuclear Missile",
  "Terran Civilian",
  "Sarah Kerrigan",
  "Sarah Kerrigan (Ghost)",
  "Alan Schezar",
  "Alan Schezar (Goliath)",
  "Alan Schezar Turret",
  "Alan Turret",
  "Jim Raynor (Vulture)",
  "Jim Raynor (Marine)",
  "Tom Kazansky",
  "Tom Kazansky (Wraith)",
  "Magellan",
  "Magellan (Science Vessel)",
  "Edmund Duke (Tank Mode)",
  "Edmund Duke (Siege Tank)",
  "Edmund Duke Turret (Tank Mode)",
  "Duke Turret type   1",
  "Edmund Duke (Siege Mode)",
  "Edmund Duke Turret (Siege Mode)",
  "Duke Turret type   2",
  "Arcturus Mengsk",
  "Arcturus Mengsk (Battlecruiser)",
  "Hyperion",
  "Hyperion (Battlecruiser)",
  "Norad II (Battlecruiser)",
  "Terran Siege Tank (Siege Mode)",
  "Siege Tank Turret (Siege Mode)",
  "Tank Turret type   2",
  "Terran Firebat",
  "Scanner Sweep (Unit)",
  "Terran Medic",
  "Zerg Larva",
  "Zerg Egg",
  "Zerg Zergling",
  "Zerg Hydralisk",
  "Zerg Ultralisk",
  "Zerg Broodling",
  "Zerg Drone",
  "Zerg Overlord",
  "Zerg Mutalisk",
  "Zerg Guardian",
  "Zerg Queen",
  "Zerg Defiler",
  "Zerg Scourge",
  "Torrasque",
  "Torrasque (Ultralisk)",
  "Matriarch",
  "Matriarch (Queen)",
  "Infested Terran",
  "Infested Kerrigan",
  "Infested Kerrigan (Infested Terran)",
  "Unclean One",
  "Unclean One (Defiler)",
  "Hunter Killer",
  "Hunter Killer (Hydralisk)",
  "Devouring One",
  "Devouring One (Zergling)",
  "Kukulza (Mutalisk)",
  "Kukulza (Guardian)",
  "Yggdrasill",
  "Yggdrasill (Overlord)",
  "Terran Valkyrie",
  "Mutalisk Cocoon",
  "Cocoon",
  "Protoss Corsair",
  "Protoss Dark Templar",
  "Protoss Dark Templar (Unit)",
  "Zerg Devourer",
  "Protoss Dark Archon",
  "Protoss Probe",
  "Protoss Zealot",
  "Protoss Dragoon",
  "Protoss High Templar",
  "Protoss Archon",
  "Protoss Shuttle",
  "Protoss Scout",
  "Protoss Arbiter",
  "Protoss Carrier",
  "Protoss Interceptor",
  "Dark Templar",
  "Dark Templar (Hero)",
  "Protoss Dark Templar (Hero)",
  "Zeratul",
  "Zeratul (Dark Templar)",
  "Tassadar/Zeratul",
  "Tassadar/Zeratul (Archon)",
  "Fenix (Zealot)",
  "Fenix (Dragoon)",
  "Tassadar (Unit)",
  "Tassadar (Templar)",
  "Mojo",
  "Mojo (Scout)",
  "Warbringer",
  "Warbringer (Reaver)",
  "Gantrithor",
  "Gantrithor (Carrier)",
  "Protoss Reaver",
  "Protoss Observer",
  "Protoss Scara",
  "Danimoth",
  "Danimoth (Arbiter)",
  "Aldaris",
  "Aldaris (Templar)",
  "Artanis",
  "Artanis (Scout)",
  "Rhynadon",
  "Rhynadon (Badlands)",
  "Rhynadon (Badlands Critter)",
  "Bengalaas",
  "Bengalaas (Jungle)",
  "Bengalaas (Jungle Critter)",
  "Cargo Ship",
  "Cargo Ship (Unused)",
  "Unused type   1",
  "Unused type   2",
  "Mercenary Gunship",
  "Mercenary Gunship (Unused)",
  "Scantid",
  "Scantid (Desert)",
  "Scantid (Desert Critter)",
  "Kakaru",
  "Kakaru (Twilight)",
  "Kakaru (Twilight Critter)",
  "Ragnasaur",
  "Ragnasaur (Ashworld)",
  "Ragnasaur (Ashworld Critter)",
  "Ursadon",
  "Ursadon (Ice World)",
  "Ursadon (Ice World Critter)",
  "Lurker Egg",
  "Zerg Lurker Egg",
  "Raszagal",
  "Raszagal (Corsair)",
  "Samir Duran",
  "Samir Duran (Ghost)",
  "Alexei Stukov",
  "Alexei Stukov (Ghost)",
  "Map Revealer",
  "Gerard DuGalle",
  "Gerard DuGalle (Ghost)",
  "Gerard DuGalle (BattleCruiser)",
  "Zerg Lurker",
  "Infested Duran",
  "Infested Duran (Infested Terran)",
  "Disruption Web (Unit)",
  "Disruption Field",
  "Terran Command Center",
  "Terran Comsat Station",
  "Terran Nuclear Silo",
  "Terran Supply Depot",
  "Terran Refinery",
  "Terran Barracks",
  "Terran Academy",
  "Terran Factory",
  "Terran Starport",
  "Terran Control Tower",
  "Terran Science Facility",
  "Terran Covert Ops",
  "Terran Physics La",
  "Starbase",
  "Starbase (Unused)",
  "Unused Terran Bldg type   1",
  "Terran Machine Shop",
  "Repair Bay",
  "Repair Bay (Unused)",
  "Unused Terran Bldg type   2",
  "Terran Engineering Bay",
  "Terran Armory",
  "Terran Missile Turret",
  "Terran Bunker",
  "Norad II (Crashed)",
  "Norad II (Crashed Battlecruiser)",
  "Ion Cannon",
  "Uraj Crystal",
  "Khalis Crystal",
  "Infested Command Center",
  "Zerg Hatchery",
  "Zerg Lair",
  "Zerg Hive",
  "Zerg Nydus Canal",
  "Zerg Hydralisk Den",
  "Zerg Defiler Mound",
  "Zerg Greater Spire",
  "Zerg Queen's Nest",
  "Zerg Evolution Chamber",
  "Zerg Ultralisk Cavern",
  "Zerg Spire",
  "Zerg Spawning Pool",
  "Zerg Creep Colony",
  "Zerg Spore Colony",
  "Unused Zerg Bldg",
  "Unused Zerg Building1",
  "Zerg Sunken Colony",
  "Zerg Overmind (With Shell)",
  "Zerg Overmind",
  "Zerg Extractor",
  "Mature Chrysalis",
  "Mature Crysalis",
  "Zerg Cerebrate",
  "Zerg Cerebrate Daggoth",
  "Unused Zerg Building2",
  "Protoss Nexus",
  "Protoss Robotics Facility",
  "Protoss Pylon",
  "Protoss Assimilator",
  "Protoss Unused type   1",
  "Unused Protoss Building1",
  "Protoss Observatory",
  "Protoss Gateway",
  "Protoss Unused type   2",
  "Unused Protoss Building2",
  "Protoss Photon Cannon",
  "Protoss Citadel of Adun",
  "Protoss Cybernetics Core",
  "Protoss Templar Archives",
  "Protoss Forge",
  "Protoss Stargate",
  "Stasis Cell/Prison",
  "Protoss Fleet Beacon",
  "Protoss Arbiter Tribunal",
  "Protoss Robotics Support Bay",
  "Protoss Shield Battery",
  "Khaydarin Crystal Formation",
  "Protoss Temple",
  "Xel'Naga Temple",
  "Mineral Field (Type 1)",
  "Mineral Field (Type 2)",
  "Mineral Field (Type 3)",
  "Cave",
  "Cave (Unused)",
  "Cave-in",
  "Cave-in (Unused)",
  "Cantina",
  "Cantina (Unused)",
  "Mining Platform",
  "Mining Platform (Unused)",
  "Independent Command Center",
  "Independent Command Center (Unused)",
  "Independent Starport",
  "Independent Starport (Unused)",
  "Jump Gate",
  "Independent Jump Gate (Unused)",
  "Ruins (Unused)",
  "Kyadarin Crystal Formation",
  "Khaydarin Crystal Formation (Unused)",
  "Vespene Geyser",
  "Warp Gate",
  "Psi Disrupter",
  "Zerg Marker",
  "Terran Marker",
  "Protoss Marker",
  "Zerg Beacon",
  "Terran Beacon",
  "Protoss Beacon",
  "Zerg Flag Beacon",
  "Terran Flag Beacon",
  "Protoss Flag Beacon",
  "Power Generator",
  "Overmind Cocoon",
  "Dark Swarm (Unit)",
  "Floor Missile Trap",
  "Floor Hatch (Unused)",
  "Floor Hatch (UNUSED)",
  "Left Upper Level Door",
  "Right Upper Level Door",
  "Left Pit Door",
  "Right Pit Door",
  "Floor Gun Trap",
  "Left Wall Missile Trap",
  "Left Wall Flame Trap",
  "Right Wall Missile Trap",
  "Right Wall Flame Trap",
  "Start Location",
  "Flag",
  "Young Chrysalis",
  "Psi Emitter",
  "Data Disc",
  "Khaydarin Crystal",
  "Mineral Chunk (Type 1)",
  "Mineral Chunk (Type 2)",
  "Mineral Cluster Type 1",
  "Mineral Cluster Type 2",
  "Vespene Orb (Protoss Type 1)",
  "Vespene Orb (Protoss Type 2)",
  "Protoss Vespene Gas Orb Type 1",
  "Protoss Vespene Gas Orb Type 2",
  "Vespene Sac (Zerg Type 1)",
  "Vespene Sac (Zerg Type 2)",
  "Zerg Vespene Gas Sac Type 1",
  "Zerg Vespene Gas Sac Type 2",
  "Vespene Tank (Terran Type 1)",
  "Vespene Tank (Terran Type 2)",
  "Terran Vespene Gas Tank Type 1",
  "Terran Vespene Gas Tank Type 2",
  "Gauss Rifle (Marine)",
  "Gauss Rifle (Jim Raynor)",
  "C-10 Canister Rifle (Ghost)",
  "C-10 Canister Rifle (Sarah Kerrigan)",
  "Fragmentation Grenade (Vulture)",
  "Fragmentation Grenade (Jim Raynor)",
  "Twin Autocannons (Goliath)",
  "Hellfire Missile Pack (Goliath)",
  "Twin Autocannons (Alan Schezar)",
  "Hellfire Missile Pack (Alan Schezar)",
  "Arclite Cannon (Siege Tank)",
  "Arclite Cannon (Edmund Duke)",
  "Fusion Cutter",
  "Fusion Cutter (Harvest)",
  "Gemini Missiles (Wraith)",
  "Burst Lasers (Wraith)",
  "Gemini Missiles (Tom Kazansky)",
  "Burst Lasers (Tom Kazansky)",
  "ATS Laser Battery (Battlecruiser)",
  "ATA Laser Battery (Battlecruiser)",
  "ATS Laser Battery (Norad II)",
  "ATA Laser Battery (Norad II)",
  "ATS Laser Battery (Hyperion)",
  "ATA Laser Battery (Hyperion)",
  "Flame Thrower (Firebat)",
  "Flame Thrower (Gui Montag)",
  "Arclite Shock Cannon (Siege Tank)",
  "Arclite Shock Cannon (Edmund Duke)",
  "Longbolt Missile",
  "Nuclear Strike (Weapon)",
  "EMP Shockwave (Weapon)",
  "Claws (Zergling)",
  "Claws (Devouring One)",
  "Claws (Infested Kerrigan)",
  "Needle Spines (Hydralisk)",
  "Needle Spines (Hunter Killer)",
  "Kaiser Blades (Ultralisk)",
  "Kaiser Blades (Torrasque)",
  "Toxic Spores",
  "Spines",
  "Acid Spray (Unused 1)",
  "Acid Spray (Unused 2)",
  "Acid Spore (Guardian)",
  "Acid Spore (Kukulza)",
  "Glave Wurm (Mutalisk)",
  "Glave Wurm (Kukulza)",
  "Venom (Defiler)",
  "Venom (Unclean One)",
  "Suicide (Infested Terran)",
  "Seeker Spores",
  "Subterranean Tentacle",
  "Suicide (Scourge)",
  "Particle Beam",
  "Psi Blades (Zealot)",
  "Psi Blades (Fenix)",
  "Warp Blades (Dark Templar Hero)",
  "Warp Blades (Zeratul)",
  "Phase Disruptor (Dragoon)",
  "Phase Disruptor (Fenix)",
  "Psi Assault (High Templar)",
  "Psi Assault (Tassadar)",
  "Psionic Shockwave (Archon)",
  "Psionic Shockwave (Tassadar/Zeratul)",
  "Unused72",
  "Dual Photon Blasters (Scout)",
  "Anti-matter Missiles (Scout)",
  "Dual Photon Blasters (Mojo)",
  "Anti-matter Missiles (Mojo)",
  "Phase Disruptor Cannon (Arbiter)",
  "Phase Disruptor Cannon (Danimoth)",
  "Pulse Cannon",
  "STS Photon Cannon",
  "STA Photon Cannon",
  "Scarab (Weapon)",
  "Missiles",
  "Laser Battery",
  "Tormentor Missiles",
  "Bombs",
  "Raider Gun",
  "Flechette Grenade",
  "Twin Autocannons",
  "Hellfire Missile Pack",
  "Flame Thrower",
  "Undefined Weapon Name",
  "Stim Packs (Tech)",
  "Lockdown (Weapon)",
  "EMP Shockwave (Tech)",
  "Spider Mines (Weapon)",
  "Scanner Sweep (Tech)",
  "Tank Siege Mode",
  "Defensive Matrix (Tech)",
  "Irradiate (Tech)",
  "Yamato Gun (Weapon)",
  "Cloaking Field",
  "Personnel Cloaking",
  "Research Stim Pack Tech",
  "Research Lockdown",
  "Research EMP Shockwave",
  "Research Spider Mines",
  "Research Siege Tech",
  "Research Defensive Matrix",
  "Research Irradiate",
  "Research Yamato Gun",
  "Research Cloaking Field",
  "Research Personnel Cloaking",
  "Use Stim Packs",
  "Lockdown (Cast)",
  "Use Spider Mines",
  "Scanner Sweep (Cast)",
  "Siege Mode (Cast)",
  "Tank Mode (Cast)",
  "Activate Defensive Matrix",
  "Activate EMP Shockwave",
  "Irradiate (Cast)",
  "Yamato Gun (Cast)",
  "Cloak (Cast)",
  "Decloak (Cast)",
  "Stim Packs:",
  "Stim Packs: Research at Academy",
  "Lockdown:",
  "Lockdown: Research at Covert Ops",
  "Spider Mines:",
  "Spider Mines: Research at Machine Shop",
  "Siege Mode:",
  "Siege Mode: Research at Machine Shop",
  "Defensive Matrix:",
  "Defensive Matrix: Research at Science Facility",
  "EMP Shockwave:",
  "EMP Shockwave: Research at Science Facility",
  "Irradiate:",
  "Irradiate: Research at Science Facility",
  "Yamato Gun:",
  "Yamato Gun: Research at Physics La",
  "Cloaking Field:",
  "Cloaking Field: Research at Control Tower",
  "Personnel Cloaking:",
  "Personnel Cloaking: Research at Covert Ops",
  "Burrowing",
  "Infestation",
  "Spawn Broodling (Tech)",
  "Dark Swarm (Tech)",
  "Parasite (Tech)",
  "Plague (Tech)",
  "Consume (Tech)",
  "Ensnare (Tech)",
  "Evolve Burrow",
  "Evolve Infestation",
  "Evolve Spawn Broodling",
  "Evolve Dark Swarm",
  "Evolve Parasite",
  "Evolve Plague",
  "Evolve Ensnare",
  "Evolve Consume",
  "Burrow (Cast)",
  "Unburrow (Cast)",
  "Infest Terran Command Center",
  "Spawn Broodling (Cast)",
  "Dark Swarm (Cast)",
  "Parasite (Cast)",
  "Plague (Cast)",
  "Consume (Defiler)",
  "Consume (Infested Kerrigan)",
  "Ensnare (Cast)",
  "Burrow:",
  "Burrow: Evolve at Hatchery",
  "Infest:",
  "Infest: Evolve at Queen's Nest",
  "Spawn Broodlings:",
  "Spawn Broodlings: Evolve at Queen's Nest",
  "Dark Swarm:",
  "Dark Swarm: Evolve at Defiler Mound",
  "Parasite:",
  "Parasite: Evolve at Queen's Nest",
  "Plague:",
  "Plague: Evolve at Defiler Mound",
  "Consume:",
  "Consume: Evolve at Defiler Mound",
  "Ensnare:",
  "Ensnare: Evolve at Queen's Nest",
  "Psionic Storm (Unused)",
  "Hallucination (Unused)",
  "Recall (Unused)",
  "Stasis Field (Unused)",
  "Archon Warp (Unused)",
  "Develop Psionic Storm",
  "Develop Hallucination",
  "Develop Recall",
  "Develop Stasis Field",
  "Develop Archon Warp",
  "Psionic Storm (Cast)",
  "Hallucination (Cast)",
  "Recall (Cast)",
  "Stasis Field (Cast)",
  "Archon Warp (Cast)",
  "Psionic Storm:",
  "Psionic Storm: Develop at Templar Archives",
  "Hallucination:",
  "Hallucination: Develop at Templar Archives",
  "Recall:",
  "Recall: Develop at Arbiter Tribunal",
  "Stasis Field:",
  "Stasis Field: Develop at Arbiter Tribunal",
  "Archon Warp: (Templar Archives)",
  "Archon Warp: Research at Templar Archives",
  "Archon Warp: (High Templar)",
  "Archon Warp: Select 2 or more Templars",
  "Terran Infantry Armor",
  "Terran Vehicle Plating",
  "Terran Ship Plating",
  "Zerg Carapace",
  "Zerg Flyer Carapace",
  "Protoss Armor",
  "Protoss Plating",
  "Terran Infantry Weapons",
  "Terran Vehicle Weapons",
  "Terran Ship Weapons",
  "Zerg Melee Attacks",
  "Zerg Missile Attacks",
  "Zerg Flyer Attacks",
  "Protoss Ground Weapons",
  "Protoss Air Weapons",
  "Protoss Plasma Shields",
  "U-238 Shells",
  "Ion Thrusters",
  "Burst Lasers",
  "Titan Reactor",
  "Ocular Implants",
  "Moebius Reactor",
  "Apollo Reactor",
  "Colossus Reactor",
  "Ventral Sacs",
  "Antennae",
  "Pneumatized Carapace",
  "Metabolic Boost",
  "Adrenal Glands",
  "Muscular Augments",
  "Grooved Spines",
  "Gamete Meiosis",
  "Metasynaptic Node",
  "Singularity Charge",
  "Leg Enhancements",
  "Scarab Damage",
  "Reaver Capacity",
  "Gravitic Drive",
  "Sensor Array",
  "Gravitic Boosters",
  "Khaydarin Amulet",
  "Apial Sensors",
  "Gravitic Thrusters",
  "Carrier Capacity",
  "Khaydarin Core",
  "Upgrade Infantry Armor",
  "Upgrade Vehicle Plating",
  "Upgrade Ship Plating",
  "Evolve Carapace",
  "Evolve Flyer Carapace",
  "Upgrade Ground Armor",
  "Upgrade Air Armor",
  "Upgrade Infantry Weapons",
  "Upgrade Vehicle Weapons",
  "Upgrade Ship Weapons",
  "Upgrade Melee Attacks",
  "Upgrade Missile Attacks",
  "Upgrade Flyer Attacks",
  "Upgrade Ground Weapons",
  "Upgrade Air Weapons",
  "Upgrade Plasma Shields",
  "Research U-238 Shells",
  "Research Ion Thrusters",
  "Research Burst Lasers",
  "Research Titan Reactor",
  "Research Ocular Implants",
  "Research Moebius Reactor",
  "Research Apollo Reactor",
  "Research Colossus Reactor",
  "Evolve Ventral Sacs",
  "Evolve Antennae",
  "Evolve Pneumatized Carapace",
  "Evolve Metabolic Boost",
  "Evolve Adrenal Glands",
  "Evolve Muscular Augments",
  "Evolve Grooved Spines",
  "Evolve Gamete Meiosis",
  "Evolve Metasynaptic Node",
  "Develop Singularity Charge",
  "Develop Leg Enhancements",
  "Upgrade Scarab Damage",
  "Increase Reaver Capacity",
  "Develop Gravitic Drive",
  "Develop Sensor Array",
  "Develop Gravitic Booster",
  "Develop Khaydarin Amulet",
  "Develop Apial Sensors",
  "Develop Gravitic Thrusters",
  "Increase Carrier Capacity",
  "Develop Khaydarin Core",
  "Infantry Armor L1 Require:",
  "Infantry Armor L2 Require:",
  "Infantry Armor L3 Require:",
  "Infantry Weapons L1 Require:",
  "Infantry Weapons L2 Require:",
  "Infantry Weapons L3 Require:",
  "Vehicle Weapons L1 Require:",
  "Vehicle Weapons L2 Require:",
  "Vehicle Weapons L3 Require:",
  "Vehicle Plating L1 Requires:",
  "Vehicle Plating L2 Requires:",
  "Vehicle Plating L3 Requires:",
  "Ship Weapons L1 Require:",
  "Ship Weapons L2 Require:",
  "Ship Weapons L3 Require:",
  "Ship Plating L1 Requires:",
  "Ship Plating L2 Requires:",
  "Ship Plating L3 Requires:",
  "Melee Attacks L1 Require:",
  "Melee Attacks L2 Require:",
  "Melee Attacks L3 Require:",
  "Missile Attacks L1 Require:",
  "Missile Attacks L2 Require:",
  "Missile Attacks L3 Require:",
  "Carapace L1 Requires:",
  "Carapace L2 Requires:",
  "Carapace L3 Requires:",
  "Flyer Attacks L1 Require:",
  "Flyer Attacks L2 Require:",
  "Flyer Attacks L3 Require:",
  "Flyer Carapace L1 Requires:",
  "Flyer Carapace L2 Requires:",
  "Flyer Carapace L3 Requires:",
  "Adrenal Glands Require:",
  "Ground Weapons L1 Require:",
  "Ground Weapons L2 Require:",
  "Ground Weapons L3 Require:",
  "Air Weapons L1 Require:",
  "Air Weapons L2 Require:",
  "Air Weapons L3 Require:",
  "Ground Armor L1 Requires:",
  "Ground Armor L2 Requires:",
  "Ground Armor L3 Requires:",
  "Air Armor L1 Requires:",
  "Air Armor L2 Requires:",
  "Air Armor L3 Requires:",
  "Shields L1 Require:",
  "Shields L2 Require:",
  "Shields L3 Require:",
  "Recruit (Unused)",
  "Private (Marine Unused)",
  "Private (SCV Unused)",
  "Corporal (Unused)",
  "Specialist (Unused)",
  "Sergeant (Unused)",
  "First Sergeant (Goliath Unused)",
  "Master Sergeant (Unused)",
  "Warrant Officer (Unused)",
  "Captain (Unused)",
  "Major (Unused)",
  "Lt Commander (Unused)",
  "First Sergeant (Gui Montag Unused)",
  "Sergeant Major (Unused)",
  "Colonel (Unused)",
  "Commodore (Unused)",
  "Marshal (Unused)",
  "Lieutenant (Unused)",
  "General (Unused)",
  "Captain Raynor (Unused)",
  "General Duke (Unused)",
  "Admiral (Unused)",
  "Tassadar (Unused)",
  "Interceptors (Unused)",
  "ESC",
  "Morph to Zerglings",
  "Morph to Hydralisk",
  "Morph to Ultralisk",
  "Morph to Drone",
  "Morph to Overlord",
  "Morph to Mutalisk",
  "Guardian Aspect (Cast)",
  "Morph to Queen",
  "Morph to Defiler",
  "Morph to Scourge",
  "Train Infested Terran",
  "Train Marine",
  "Train Ghost",
  "Train Firebat",
  "Build Vulture",
  "Build Goliath",
  "Build Siege Tank",
  "Build SCV",
  "Build Wraith",
  "Build Science Vessel",
  "Build Dropship",
  "Build Battlecruiser",
  "Arm Nuclear Silo",
  "Build Observer",
  "Build Probe",
  "Warp in Zealot",
  "Warp in Dragoon",
  "Warp in High Templar",
  "Build Shuttle",
  "Warp in Scout",
  "Warp in Arbiter",
  "Warp in Carrier",
  "Build Interceptor",
  "Build Reaver",
  "Build Scara",
  "Hire Merc Biker",
  "Hire Merc Gunship",
  "Hire Raider",
  "Mutate into Hatchery",
  "Mutate into Creep Colony",
  "Mutate into Extractor",
  "Mutate into Spawning Pool",
  "Mutate into Evolution Chamber",
  "Mutate into Hydralisk Den",
  "Mutate into Nydus Canal",
  "Mutate into Spire",
  "Mutate into Queen's Nest",
  "Mutate into Ultralisk Cavern",
  "Mutate into Defiler Mound",
  "Mutate into Lair",
  "Mutate into Hive",
  "Mutate into Greater Spire",
  "Mutate into Spore Colony",
  "Mutate into Sunken Colony",
  "Place Nydus Canal Exit",
  "Warp in Nexus",
  "Warp in Pylon",
  "Warp in Assimilator",
  "Warp in Gateway",
  "Warp in Forge",
  "Warp in Photon Cannon",
  "Warp in Cybernetics Core",
  "Warp in Shield Battery",
  "Warp in Robotics Facility",
  "Warp in Observatory",
  "Warp in Citadel of Adun",
  "Warp in Templar Archives",
  "Warp in Stargate",
  "Warp in Fleet Beacon",
  "Warp in Arbiter Tribunal",
  "Warp in Robotics Support Bay",
  "Build Command Center",
  "Build Supply Depot",
  "Build Refinery",
  "Build Barracks",
  "Build Engineering Bay",
  "Build Missile Turret",
  "Build Academy",
  "Build Bunker",
  "Build Factory",
  "Build Starport",
  "Build Science Facility",
  "Build Armory",
  "Build Comsat Station",
  "Build Nuclear Silo",
  "Build Control Tower",
  "Build Covert Ops",
  "Build Physics La",
  "Build Machine Shop",
  "Move",
  "Stop (Cast)",
  "Attack (Cast)",
  "Patrol (Cast)",
  "Hold Position (Cast)",
  "Way Points",
  "Land",
  "Liftoff",
  "Set Rally Point",
  "Recharge Shields (Cast)",
  "Select Larva",
  "Gather",
  "Return Cargo",
  "Repair (Cast)",
  "Build Structure",
  "Build Advanced Structure",
  "Basic Mutation",
  "Advanced Mutation",
  "Advanced Morph",
  "Load",
  "Unload All",
  "Nuclear Strike (Cast)",
  "Place COP",
  "ESC - Cancel (Unknown)",
  "ESC - Cancel (Normal)",
  "ESC - Cancel Construction",
  "ESC - Cancel Unit Training",
  "ESC - Cancel Upgrade",
  "ESC - Cancel Research",
  "ESC - Cancel Last",
  "ESC - Cancel Addon",
  "ESC - Cancel Morph",
  "ESC - Cancel Mutation (Build)",
  "ESC - Cancel Infestation",
  "ESC - Cancel Mutation (Lair)",
  "ESC - Cancel Nuclear Strike",
  "ESC - Halt Construction",
  "Ghost Requires:",
  "Firebat Requires:",
  "Goliath Requires:",
  "Siege Tank Requires:",
  "Science Vessel Requires:",
  "Dropship Requires:",
  "Battlecruiser Requires:",
  "Comsat Station Requires:",
  "Nuclear Silo Requires:",
  "Barracks Requires:",
  "Academy Requires:",
  "Factory Requires:",
  "Starport Requires:",
  "Science Facility Requires:",
  "Engineering Bay Requires:",
  "Armory Requires:",
  "Missile Turret Requires:",
  "Bunker Requires:",
  "Dragoon Requires:",
  "Templar Requires:",
  "Arbiter Requires:",
  "Carrier Requires:",
  "Reaver Requires:",
  "Observer Requires:",
  "Gateway Requires:",
  "Forge Requires:",
  "Photon Cannon Requires:",
  "Shield Battery Requires:",
  "Cybernetics Core Requires:",
  "Robotics Facility Requires:",
  "Stargate Requires:",
  "Citadel of Adun Requires:",
  "Observatory Requires:",
  "Robotics Support Bay Requires:",
  "Fleet Beacon Requires:",
  "Templar Archives Require:",
  "Arbiter Tribunal Requires:",
  "Zerglings Require:",
  "Hydralisk Requires:",
  "Ultralisk Requires:",
  "Mutalisk Requires:",
  "Guardian Aspect Requires:",
  "Queen Requires:",
  "Defiler Requires:",
  "Scourge Require:",
  "Lair Requires:",
  "Hive Requires:",
  "Nydus Canal Requires:",
  "Hydralisk Den Requires:",
  "Spire Requires:",
  "Greater Spire Requires:",
  "Queen's Nest Requires:",
  "Evolution Chamber Requires:",
  "Ultralisk Cavern Requires:",
  "Defiler Mound Requires:",
  "Spawning Pool Requires:",
  "Spawning Pool Requires: Hatchery",
  "Spore Colony Requires:",
  "Spore Colony Requires: Evolution Chamber",
  "Sunken Colony Requires:",
  "Sunken Colony Requires: Spawning Pool",
  "Carrier Attack:",
  "Carrier Attack: Build Interceptors",
  "Reaver Attack:",
  "Reaver Attack: Build Scarabs",
  "Nuclear Strike Requires:",
  "Nuclear Strike Requires: Armed Nuclear Silo",
  "Not Implemented",
  "mk",
  "Kills:",
  "Evolving (1)",
  "Upgrading (1)",
  "Upgrading (2)",
  "Evolving (2)",
  "Researching",
  "Developing",
  "Morphing (1)",
  "Building (1)",
  "Opening Warp Gate",
  "Morphing (2)",
  "Building (2)",
  "Building (3)",
  "Damage:",
  "Armor:",
  "Shields:",
  "Mining Delay:",
  "Production",
  "Unit Ptr:",
  "Current Order:",
  "Next Order:",
  "% Complete",
  "Order:",
  "Mutating (1)",
  "Adding On",
  "Opening Warp Rift (1)",
  "Summoning",
  "Interceptors (Count)",
  "Scarabs",
  "Nukes",
  "Spider Mines (Count)",
  "Next Level:",
  "Minerals:",
  "Vespene Gas:",
  "Depleted",
  "Mutating (2)",
  "Under Construction",
  "Opening Warp Rift (2)",
  "Cancel Morph (%s)",
  "Cancel Construction (%s)",
  "Cancel Warp (%s)",
  "Cancel Upgrade",
  "Cancel Research",
  "Cancel Morph",
  "Unload Unit (%s)",
  "Click: Select Unit",
  "Show Terrain in Minimap (Tab)",
  "Hide Terrain in Minimap (Tab)",
  "Diplomacy",
  "Messaging",
  "Game Menu (F10)",
  "Control Provided:",
  "Supplies Provided:",
  "Psi Provided:",
  "Total Control:",
  "Total Supplies:",
  "Total Psi:",
  "Control Used:",
  "Supplies Used:",
  "Psi Used:",
  "Control Max:",
  "Supplies Max:",
  "Psi Max:",
  "Parasite Detected",
  "Disabled (1)",
  "Disabled (2)",
  "Unpowered",
  "Detector",
  "Hallucination (Status)",
  "Units (1)",
  "Units (2)",
  "Resources",
  "Kills",
  "Score",
  "Units to go (1)",
  "Units to go (2)",
  "Resources to go",
  "Kills to go",
  "Score to go",
  "Nowhere to return to...can't return.",
  "Too many underlings...create more Overlords.",
  "Not enough supplies...build more Supply Depots.",
  "Not enough psi...build more Pylons.",
  "Underling limit exceeded.",
  "Supply limit exceeded.",
  "Psi limit exceeded.",
  "Not enough minerals...mine more minerals.",
  "Not enough Vespene gases....harvest more gas.",
  "You can't build next to minerals or geysers.",
  "An undetected unit is in the way.",
  "You can't build off the map.",
  "You can't build near the edge of the map.",
  "You can't build there.",
  "You must explore there first.",
  "You must currently be able to see the location.",
  "Could not build there, find a Vespene Geyser to build on.",
  "You must build on the Creep.",
  "You must build near a Pylon.",
  "Couldn't reach the building site.",
  "You can't land there.",
  "Not enough energy. (1)",
  "Not enough energy. (2)",
  "Not enough energy. (3)",
  "Nothing to harvest. Find a Mine or a Vespene Geyser.",
  "Nothing to harvest. Find a Mine, or build a Refinery at a Vespene Geyser.",
  "Nothing to harvest. Find a Mine, or build an Assimilator at a Vespene Geyser.",
  "Must target severely damaged Terran Command Center.",
  "Unit's waypoint list is full.",
  "Unable to add order.",
  "Running low on orders, your last order was not processed.",
  "Not enough life remaining.",
  "Vespene Geyser depleted.",
  "Invalid target. (1)",
  "Unable to target structure. (1)",
  "Must target units.",
  "Unable to attack target.",
  "Invalid target. (2)",
  "Must target mechanical units.",
  "Invalid target. (3)",
  "Must target damaged mechanical units or damaged complete buildings.",
  "Must target Terran units.",
  "Invalid target. (4)",
  "Must target non-robotic ground units.",
  "Must target ground.",
  "Target out of range.",
  "Target is too close.",
  "Can only pick up your own transportable units.",
  "Not enough room for unit.",
  "Must gather from a Mineral Field or Vespene Geyser.",
  "Morph an Extractor there first.",
  "Build a Refinery there first.",
  "Build an Assimilator there first.",
  "Must gather gases from your own geyser.",
  "Invalid target. (5)",
  "Invalid target. (6)",
  "Invalid target. (7)",
  "Units in stasis can't be targeted.",
  "Must target non-hovering ground units.",
  "Must target passable terrain.",
  "Die",
  "Fizzle",
  "Stop (Order)",
  "Guard",
  "Player Guard",
  "Turret Guard",
  "Bunker Guard",
  "Ignore",
  "Carrier Ignore",
  "Carrier Stop",
  "Reaver Stop",
  "Attack (Order)",
  "Attack Unit",
  "Attack Fixed Range",
  "Move Attack Unit",
  "Attack Tile",
  "Hover",
  "Attack Move",
  "Atk Move EP",
  "Harass Move",
  "AI Patrol",
  "Tower",
  "Vulture Mine",
  "Carrier Attack",
  "Carrier Attack Move",
  "Stay In Range",
  "Turret Attack",
  "Nothing",
  "Drone Start Build",
  "Drone Build",
  "Drone Attack Unit",
  "Infest Mine",
  "Build",
  "Build Protoss",
  "Pylon Build",
  "Construct Building",
  "Repair (Order)",
  "Place Add-On",
  "Build Add-On",
  "Train",
  "Zerg Birth",
  "Morph",
  "Zerg Building Morph",
  "Build Self",
  "Zerg Build Self",
  "Enter Nydus Canal",
  "Protoss Build Self",
  "Follow",
  "Carrier",
  "Carrier Fight",
  "Reaver",
  "Reaver Attack",
  "Reaver Fight",
  "Reaver Hold",
  "Train Fighter",
  "Strafe Unit",
  "Scarab (Order)",
  "Return",
  "Drone Land",
  "Building Land",
  "Building Lift Off",
  "Drone Lift Off",
  "Lift Off",
  "Reasearch Tech",
  "Upgrade",
  "Larva",
  "Spawning Larva",
  "Harvest",
  "Harvest Gas",
  "Return Gas",
  "Harvest Minerals",
  "Return Minerals",
  "Enter Transport (Order)",
  "Pick Up",
  "Powerup",
  "Siege Mode (Order)",
  "Tank Mode (Order)",
  "Watch Target",
  "Initing Creep Growth",
  "Stopping Creep Growth",
  "Spread Creep",
  "Guardian Aspect (Order)",
  "Warping Archon",
  "Completing Archon Summon",
  "Hold Position (Order)",
  "Cloak (Order)",
  "Decloak (Order)",
  "Unload",
  "Move Unload",
  "Fire Yamato Gun",
  "Magna Pulse",
  "Burrow (Order)",
  "Burrowed",
  "Unburrow (Order)",
  "Cast Parasite",
  "Summon Broodlings",
  "EMP Shockwave (Order)",
  "Lockdown (Order)",
  "Nuke Wait",
  "Nuke Train",
  "Nuke Launch",
  "Nuke Paint",
  "Nuke Unit",
  "Nuke Ground",
  "Nuke Track",
  "Initializing Arbiter",
  "Cloaking nearby units",
  "Place Mine",
  "Right Click Action",
  "Left Click Action",
  "Sap Unit",
  "Sap Location",
  "Teleport",
  "Teleport to Location",
  "Place Scanner",
  "Scanner",
  "Defensive Matrix (Order)",
  "Reset Collision (1)",
  "Reset Collision (2)",
  "Patrol (Order)",
  "Computer AI",
  "Guard Post",
  "Rescue Passive",
  "Neutral",
  "Computer Return",
  "Initing Psi Provider",
  "Self Destructing",
  "Decaying creep",
  "Recharge Shields (Order)",
  "Shield Battery",
  "Rally Point",
  "CTF COP Init",
  "CTF COP",
  "Critter",
  "Hidden Gun",
  "Open Door",
  "Close Door",
  "Hide Trap",
  "Reveal Trap",
  "Enable Doodad",
  "Disable Doodad",
  "Warp In",
  "Hide and Suicide",
  "Fatal",
  "Nuclear launch detected.",
  "Terran Custom Level",
  "Terran Campaign Easy",
  "Terran Campaign Medium",
  "Terran Campaign Difficult",
  "Terran Campaign Area Town",
  "Terran 3 - Zerg Town",
  "Terran 5 - Terran Main Town",
  "Terran 5 - Terran Harvest Town",
  "Terran 6 - Air Attack Zerg",
  "Terran 6 - Ground Attack Zerg",
  "Terran 6 - Zerg Support Town",
  "Terran 7 - Bottom Zerg Town",
  "Terran 7 - Right Zerg Town",
  "Terran 7 - Middle Zerg Town",
  "Terran 8 - Confederate Town",
  "Terran 9 - Light Attack",
  "Terran 9 - Heavy Attack",
  "Terran 10 - Confederate Towns",
  "Terran 11 - Zerg Town",
  "Terran 11 - Lower Protoss Town",
  "Terran 11 - Upper Protoss Town",
  "Terran 12 - Nuke Town",
  "Terran 12 - Phoenix Town",
  "Terran 12 - Tank Town",
  "Protoss Custom Level",
  "Protoss Campaign Easy",
  "Protoss Campaign Medium",
  "Protoss Campaign Difficult",
  "Protoss Campaign Area Town",
  "Protoss 1 - Zerg Town",
  "Protoss 2 - Zerg Town",
  "Protoss 3 - Unused",
  "Protoss 3 - Air Zerg Town",
  "Protoss 3 - Ground Zerg Town",
  "Protoss 4 - Zerg Town",
  "Protoss 4 - Zerg Town (unused?)",
  "Protoss 5 - Zerg Town Island",
  "Protoss 5 - Zerg Town Base",
  "Protoss 6 - incomplete",
  "Protoss 7 - Left Protoss Town",
  "Protoss 7 - Right Protoss Town",
  "Protoss 7 - Shrine Protoss",
  "Protoss 8 - Left Protoss Town",
  "Protoss 8 - Right Protoss Town",
  "Protoss 8 - Protoss Defenders",
  "Protoss 9 - Ground Zerg",
  "Protoss 9 - Air Zerg",
  "Protoss 9 - Spell Zerg",
  "Protoss 10 - Mini-Towns",
  "Protoss 10 - Mini-Town Master",
  "Protoss 10 - Overmind Defenders",
  "Zerg Custom Level",
  "Zerg Campaign Easy",
  "Zerg Campaign Medium",
  "Zerg Campaign Difficult",
  "Zerg Campaign Area Town",
  "Zerg 1 - Terran Town",
  "Zerg 2 - Protoss Town",
  "Zerg 3 - Terran Town",
  "Zerg 4 - Right Terran Town",
  "Zerg 4 - Lower Terran Town",
  "Zerg 5 - incomplete",
  "Zerg 6 - Protoss Town",
  "Zerg 7 - Ground Town",
  "Zerg 7 - Air Town",
  "Zerg 7 - Support Town",
  "Zerg 8 - Scout Town",
  "Zerg 8 - Templar Town",
  "Zerg 9 - Teal Protoss",
  "Zerg 9 - Left Yellow Protoss",
  "Zerg 9 - Right Yellow Protoss",
  "Zerg 9 - Left Orange Protoss",
  "Zerg 9 - Right Orange Protoss",
  "Zerg 10 - Left Teal (Attack)",
  "Zerg 10 - Right Teal (Support)",
  "Zerg 10 - Left Yellow (Support)",
  "Zerg 10 - Right Yellow (Attack)",
  "Zerg 10 - Red Protoss",
  "Set a Default Staging Area",
  "Send All Units on Strategic Suicide Missions",
  "Send All Units on Random Suicide Missions",
  "Set Player to Enemy",
  "Set Player to Ally",
  "Move Dark Templars to Region",
  "Switch Computer Player to Rescue Passive",
  "Enter Closest Bunker",
  "Value This Area Higher",
  "Clear Previous Combat Data",
  "Debug Script 1 (general)",
  "Debug Script 2 (general)",
  "Debug Script 3 (general)",
  "Debug Script 4 (general)",
  "Debug Script 5 (general)",
  "Debug Script 1 (location)",
  "Debug Script 2 (location)",
  "Debug Script 3 (location)",
  "Debug Script 4 (location)",
  "Debug Script 5 (location)",
  "Structure",
  "Structure Wall",
  "Cliff (Badlands)",
  "High Dirt (Badlands)",
  "Grass (Badlands)",
  "High Grass (Badlands)",
  "Dirt (Badlands)",
  "Rocky Ground (Badlands)",
  "Asphalt",
  "Water (Badlands)",
  "Coastal Cliff",
  "Jungle",
  "High Jungle",
  "Ruins (Jungle)",
  "High Ruins",
  "Temple Wall",
  "High Temple Wall",
  "Dark Platform",
  "High Plating",
  "Plating (Space)",
  "Platform",
  "Platform Wall",
  "Low Platform",
  "Low Platform Wall",
  "Rusty Pit Wall",
  "Rusty Pit",
  "Solar Array",
  "Dirt (Ashworld)",
  "High Dirt (Ashworld)",
  "Shale",
  "Cliff (Ashworld)",
  "Floor",
  "Wall",
  "Substructure",
  "Substructure Wall",
  "Plating (Installation)",
  "Bridges (1)",
  "Bridges (2)",
  "Elevated Catwalk Ramps",
  "Bridges (3)",
  "Tar",
  "Tar Cliff",
  "Dirt (Desert)",
  "Dried Mud",
  "Sand Dunes",
  "Rocky Ground (Desert)",
  "Crags",
  "Sandy Sunken Pit",
  "Compound",
  "High Dirt (Desert)",
  "High Sand Dunes",
  "High Crags",
  "High Sandy Sunken Pit",
  "High Compound",
  "Water (Ice World)",
  "Snow",
  "Moguls",
  "Dirt (Ice World)",
  "Rocky Snow",
  "Grass (Ice World)",
  "Ice",
  "Outpost",
  "High Snow",
  "High Dirt (Ice World)",
  "High Grass (Ice World)",
  "High Ice",
  "High Outpost",
  "Water (Twilight)",
  "Dirt (Twilight)",
  "Mud",
  "Crushed Rock",
  "Crevices",
  "Flagstones",
  "Sunken Ground",
  "Basilica",
  "High Dirt (Twilight)",
  "High Crushed Rock",
  "High Flagstones",
  "High Sunken Ground",
  "High Basilica",
  "Terran Campaign Insane",
  "Protoss Campaign Insane",
  "Zerg Campaign Insane",
  "Terran 1 - Electronic Distribution",
  "Terran 2 - Electronic Distribution",
  "Terran 3 - Electronic Distribution",
  "Terran 1 - Shareware",
  "Terran 2 - Shareware",
  "Terran 3 - Shareware",
  "Terran 4 - Shareware",
  "Terran 5 - Shareware",
  "Halo Rockets",
  "Corrosive Acid",
  "Subterranean Spines",
  "Neutron Flare",
  "Mind Control (Weapon)",
  "Healing",
  "Restoration (Tech)",
  "Optical Flare (Tech)",
  "Research Restoration",
  "Research Optical Flare",
  "Heal",
  "Restoration (Cast)",
  "Optical Flare (Cast)",
  "Restoration:",
  "Restoration: Research at Academy",
  "Optical Flare:",
  "Optical Flare: Research at Academy",
  "Lurker Aspect",
  "Evolve Lurker Aspect",
  "Lurker Aspect: (Hydralisk Den)",
  "Lurker Aspect: Requires Lair",
  "Disruption Web (Tech)",
  "Mind Control (Tech)",
  "Dark Archon Meld (Tech)",
  "Feedback (Tech)",
  "Maelstrom (Tech)",
  "Develop Disruption We",
  "Develop Mind Control",
  "Develop Feedback",
  "Develop Maelstrom",
  "Dark Archon Meld (Cast)",
  "Disruption Web (Cast)",
  "Mind Control (Cast)",
  "Feedback (Cast)",
  "Maelstrom (Cast)",
  "Disruption Web:",
  "Disruption Web: Develop at Fleet Beacon",
  "Mind Control:",
  "Mind Control: Research at Templar Archives",
  "Dark Archon Meld:",
  "Dark Archon Meld: Research at Templar Archives",
  "Dark Archon Warp:",
  "Dark Archon Warp: Select 2 or more Dark Templars",
  "Feedback:",
  "Feedback: No requirement",
  "Maelstrom:",
  "Maelstrom: Develop at Templar Archives",
  "Caduceus Reactor",
  "Charon Booster",
  "Anabolic Synthesis",
  "Chitinous Plating",
  "Argus Jewel",
  "Argus Talisman",
  "Research Caduceus Reactor",
  "Research Charon Booster",
  "Evolve Anabolic Synthesis",
  "Evolve Chitinous Plating",
  "Develop Argus Jewel",
  "Develop Argus Talisman",
  "Research Charon Booster:",
  "Research Charon Booster: Requires Armory",
  "Devourer Aspect",
  "Morph to Lurker",
  "Train Medic",
  "Build Valkyrie",
  "Warp in Corsair",
  "Warp in Dark Templar",
  "Medic Requires:",
  "Medic Requires: Academy",
  "Valkyrie Requires:",
  "Valkyrie Requires: Attached Control Tower Armory",
  "Dark Templar Requires:",
  "Dark Templar Requires: Templar Archives",
  "Devourer Aspect Requires:",
  "Devourer Aspect Requires: Greater Spire",
  "Lurker Aspect: (Hydralisk)",
  "Lurker Aspect: Evolve at Hydralisk Den",
  "Blind",
  "Acid Spores",
  "per rocket",
  "Recruit (Rank)",
  "Private (Marine Rank)",
  "Private (SCV Rank)",
  "1st Lieutenant (Rank)",
  "Corporal (Rank)",
  "Specialist (Rank)",
  "Sergeant (Rank)",
  "First Sergeant (Goliath Rank)",
  "Master Sergeant (Rank)",
  "Warrant Officer (Rank)",
  "Captain (Rank)",
  "Major (Rank)",
  "First Sergeant (Gui Montag Rank)",
  "Sergeant Major (Rank)",
  "Colonel (Rank)",
  "Commodore (Rank)",
  "Lt Commander (Rank)",
  "Marshal (Rank)",
  "Lieutenant (Rank)",
  "General (Rank)",
  "Captain Raynor (Rank)",
  "General Duke (Rank)",
  "Admiral (Rank)",
  "Must target injured non-mechanical ground units",
  "Invalid target. (8)",
  "Must target enemy units",
  "Must target non-mechanical units.",
  "Unable to target structure. (2)",
  "Must target units with energy.",
  "Medic",
  "Medic Heal",
  "Restoration (Order)",
  "Cast Disruption We",
  "Mind Control (Order)",
  "Warping Dark Archon",
  "Cast Feedback",
  "Cast Optical Flare",
  "Cast Shockwave",
  "Heal Move",
  "Medic Hold Position",
  "Junk Yard Dog",
  "Terran Expansion Custom Level",
  "Protoss Expansion Custom Level",
  "Zerg Expansion Custom Level",
  "Brood Wars Protoss 1 - Town A",
  "Brood Wars Protoss 1 - Town ",
  "Brood Wars Protoss 1 - Town C",
  "Brood Wars Protoss 1 - Town D",
  "Brood Wars Protoss 1 - Town E",
  "Brood Wars Protoss 1 - Town F",
  "Brood Wars Protoss 2 - Town A",
  "Brood Wars Protoss 2 - Town ",
  "Brood Wars Protoss 2 - Town C",
  "Brood Wars Protoss 2 - Town D",
  "Brood Wars Protoss 2 - Town E",
  "Brood Wars Protoss 2 - Town F",
  "Brood Wars Protoss 3 - Town A",
  "Brood Wars Protoss 3 - Town ",
  "Brood Wars Protoss 3 - Town C",
  "Brood Wars Protoss 3 - Town D",
  "Brood Wars Protoss 3 - Town E",
  "Brood Wars Protoss 3 - Town F",
  "Brood Wars Protoss 4 - Town A",
  "Brood Wars Protoss 4 - Town ",
  "Brood Wars Protoss 4 - Town C",
  "Brood Wars Protoss 4 - Town D",
  "Brood Wars Protoss 4 - Town E",
  "Brood Wars Protoss 4 - Town F",
  "Brood Wars Protoss 5 - Town A",
  "Brood Wars Protoss 5 - Town ",
  "Brood Wars Protoss 5 - Town C",
  "Brood Wars Protoss 5 - Town D",
  "Brood Wars Protoss 5 - Town E",
  "Brood Wars Protoss 5 - Town F",
  "Brood Wars Protoss 6 - Town A",
  "Brood Wars Protoss 6 - Town ",
  "Brood Wars Protoss 6 - Town C",
  "Brood Wars Protoss 6 - Town D",
  "Brood Wars Protoss 6 - Town E",
  "Brood Wars Protoss 6 - Town F",
  "Brood Wars Protoss 7 - Town A",
  "Brood Wars Protoss 7 - Town ",
  "Brood Wars Protoss 7 - Town C",
  "Brood Wars Protoss 7 - Town D",
  "Brood Wars Protoss 7 - Town E",
  "Brood Wars Protoss 7 - Town F",
  "Brood Wars Protoss 8 - Town A",
  "Brood Wars Protoss 8 - Town ",
  "Brood Wars Protoss 8 - Town C",
  "Brood Wars Protoss 8 - Town D",
  "Brood Wars Protoss 8 - Town E",
  "Brood Wars Protoss 8 - Town F",
  "Brood Wars Terran 1 - Town A",
  "Brood Wars Terran 1 - Town ",
  "Brood Wars Terran 1 - Town C",
  "Brood Wars Terran 1 - Town D",
  "Brood Wars Terran 1 - Town E",
  "Brood Wars Terran 1 - Town F",
  "Brood Wars Terran 2 - Town A",
  "Brood Wars Terran 2 - Town ",
  "Brood Wars Terran 2 - Town C",
  "Brood Wars Terran 2 - Town D",
  "Brood Wars Terran 2 - Town E",
  "Brood Wars Terran 2 - Town F",
  "Brood Wars Terran 3 - Town A",
  "Brood Wars Terran 3 - Town ",
  "Brood Wars Terran 3 - Town C",
  "Brood Wars Terran 3 - Town D",
  "Brood Wars Terran 3 - Town E",
  "Brood Wars Terran 3 - Town F",
  "Brood Wars Terran 4 - Town A",
  "Brood Wars Terran 4 - Town ",
  "Brood Wars Terran 4 - Town C",
  "Brood Wars Terran 4 - Town D",
  "Brood Wars Terran 4 - Town E",
  "Brood Wars Terran 4 - Town F",
  "Brood Wars Terran 5 - Town A",
  "Brood Wars Terran 5 - Town ",
  "Brood Wars Terran 5 - Town C",
  "Brood Wars Terran 5 - Town D",
  "Brood Wars Terran 5 - Town E",
  "Brood Wars Terran 5 - Town F",
  "Brood Wars Terran 6 - Town A",
  "Brood Wars Terran 6 - Town ",
  "Brood Wars Terran 6 - Town C",
  "Brood Wars Terran 6 - Town D",
  "Brood Wars Terran 6 - Town E",
  "Brood Wars Terran 6 - Town F",
  "Brood Wars Terran 7 - Town A",
  "Brood Wars Terran 7 - Town ",
  "Brood Wars Terran 7 - Town C",
  "Brood Wars Terran 7 - Town D",
  "Brood Wars Terran 7 - Town E",
  "Brood Wars Terran 7 - Town F",
  "Brood Wars Terran 8 - Town A",
  "Brood Wars Terran 8 - Town ",
  "Brood Wars Terran 8 - Town C",
  "Brood Wars Terran 8 - Town D",
  "Brood Wars Terran 8 - Town E",
  "Brood Wars Terran 8 - Town F",
  "Brood Wars Zerg 1 - Town A",
  "Brood Wars Zerg 1 - Town ",
  "Brood Wars Zerg 1 - Town C",
  "Brood Wars Zerg 1 - Town D",
  "Brood Wars Zerg 1 - Town E",
  "Brood Wars Zerg 1 - Town F",
  "Brood Wars Zerg 2 - Town A",
  "Brood Wars Zerg 2 - Town ",
  "Brood Wars Zerg 2 - Town C",
  "Brood Wars Zerg 2 - Town D",
  "Brood Wars Zerg 2 - Town E",
  "Brood Wars Zerg 2 - Town F",
  "Brood Wars Zerg 3 - Town A",
  "Brood Wars Zerg 3 - Town ",
  "Brood Wars Zerg 3 - Town C",
  "Brood Wars Zerg 3 - Town D",
  "Brood Wars Zerg 3 - Town E",
  "Brood Wars Zerg 3 - Town F",
  "Brood Wars Zerg 4 - Town A",
  "Brood Wars Zerg 4 - Town ",
  "Brood Wars Zerg 4 - Town C",
  "Brood Wars Zerg 4 - Town D",
  "Brood Wars Zerg 4 - Town E",
  "Brood Wars Zerg 4 - Town F",
  "Brood Wars Zerg 5 - Town A",
  "Brood Wars Zerg 5 - Town ",
  "Brood Wars Zerg 5 - Town C",
  "Brood Wars Zerg 5 - Town D",
  "Brood Wars Zerg 5 - Town E",
  "Brood Wars Zerg 5 - Town F",
  "Brood Wars Zerg 6 - Town A",
  "Brood Wars Zerg 6 - Town ",
  "Brood Wars Zerg 6 - Town C",
  "Brood Wars Zerg 6 - Town D",
  "Brood Wars Zerg 6 - Town E",
  "Brood Wars Zerg 6 - Town F",
  "Brood Wars Zerg 7 - Town A",
  "Brood Wars Zerg 7 - Town ",
  "Brood Wars Zerg 7 - Town C",
  "Brood Wars Zerg 7 - Town D",
  "Brood Wars Zerg 7 - Town E",
  "Brood Wars Zerg 7 - Town F",
  "Brood Wars Zerg 8 - Town A",
  "Brood Wars Zerg 8 - Town ",
  "Brood Wars Zerg 8 - Town C",
  "Brood Wars Zerg 8 - Town D",
  "Brood Wars Zerg 8 - Town E",
  "Brood Wars Zerg 8 - Town F",
  "Brood Wars Zerg 9 - Town A",
  "Brood Wars Zerg 9 - Town ",
  "Brood Wars Zerg 9 - Town C",
  "Brood Wars Zerg 9 - Town D",
  "Brood Wars Zerg 9 - Town E",
  "Brood Wars Zerg 9 - Town F",
  "Brood Wars Zerg 10 - Town A",
  "Brood Wars Zerg 10 - Town ",
  "Brood Wars Zerg 10 - Town C",
  "Brood Wars Zerg 10 - Town D",
  "Brood Wars Zerg 10 - Town E",
  "Brood Wars Zerg 10 - Town F",
  "Expansion Zerg Campaign Easy",
  "Expansion Zerg Campaign Medium",
  "Expansion Zerg Campaign Difficult",
  "Expansion Zerg Campaign Area Town",
  "Expansion Protoss Campaign Easy",
  "Expansion Protoss Campaign Medium",
  "Expansion Protoss Campaign Difficult",
  "Expansion Protoss Campaign Area Town",
  "Expansion Terran Campaign Easy",
  "Expansion Terran Campaign Medium",
  "Expansion Terran Campaign Difficult",
  "Expansion Terran Campaign Area Town",
  "Expansion Terran Campaign Insane",
  "Expansion Protoss Campaign Insane",
  "Expansion Zerg Campaign Insane",
  "Set Generic Command Target",
  "Make These Units Patrol",
  "Enter Transport (AIScript)",
  "Exit Transport",
  "Turn ON Shared Vision for Player 1",
  "Turn ON Shared Vision for Player 2",
  "Turn ON Shared Vision for Player 3",
  "Turn ON Shared Vision for Player 4",
  "Turn ON Shared Vision for Player 5",
  "Turn ON Shared Vision for Player 6",
  "Turn ON Shared Vision for Player 7",
  "Turn ON Shared Vision for Player 8",
  "Turn OFF Shared Vision for Player 1",
  "Turn OFF Shared Vision for Player 2",
  "Turn OFF Shared Vision for Player 3",
  "Turn OFF Shared Vision for Player 4",
  "Turn OFF Shared Vision for Player 5",
  "Turn OFF Shared Vision for Player 6",
  "Turn OFF Shared Vision for Player 7",
  "Turn OFF Shared Vision for Player 8",
  "AI Nuke Here",
  "AI Harass Here",
  "Set Unit Order To: Junk Yard Dog",
  "View Players",
  "Speed Up",
  "Play",
  "Pause",
  "Slow Down",
  "Replay Progress",
  "Paused",
  "Unlimited",
];

export const SCImage = [
  "Scourge",
  "Scourge Shadow",
  "Scourge Birth",
  "Scourge Death",
  "Scourge Explosion",
  "Broodling",
  "Broodling Shadow",
  "Broodling Remnants",
  "Infested Terran",
  "Infested Terran Shadow",
  "Infested Terran Explosion",
  "Guardian Cocoon",
  "Guardian Cocoon Shadow",
  "Defiler",
  "Defiler Shadow",
  "Defiler Birth",
  "Defiler Remnants",
  "Drone",
  "Drone Shadow",
  "Drone Birth",
  "Drone Remnants",
  "Egg",
  "Egg Shadow",
  "Egg Spawn",
  "Egg Remnants",
  "Guardian",
  "Guardian Shadow",
  "Guardian Birth",
  "Guardian Death",
  "Hydralisk",
  "Hydralisk Shadow",
  "Hydralisk Birth",
  "Hydralisk Remnants",
  "Infested Kerrigan",
  "Infested Kerrigan Shadow",
  "Needle Spines",
  "Larva",
  "Larva Remnants",
  "Mutalisk",
  "Mutalisk Shadow",
  "Mutalisk Birth",
  "Mutalisk Death",
  "Overlord",
  "Overlord Shadow",
  "Overlord Birth",
  "Overlord Death",
  "Queen",
  "Queen Shadow",
  "Queen Death",
  "Queen Birth",
  "Ultralisk",
  "Ultralisk Shadow",
  "Ultralisk Birth",
  "Ultralisk Remnants",
  "Zergling",
  "Zergling Shadow",
  "Zergling Birth",
  "Zergling Remnants",
  "Zerg Air Death Explosion (Large)",
  "Zerg Air Death Explosion (Small)",
  "Zerg Building Explosion",
  "Cerebrate",
  "Cerebrate Shadow",
  "Infested Command Center",
  "Spawning Pool",
  "Spawning Pool Shadow",
  "Evolution Chamber",
  "Evolution Chamber Shadow",
  "Creep Colony",
  "Creep Colony Shadow",
  "Hatchery",
  "Hatchery Shadow",
  "Hive",
  "Hive Shadow",
  "Lair",
  "Lair Shadow",
  "Sunken Colony",
  "Sunken Colony Shadow",
  "Mature Chrysalis",
  "Mature Chrysalis Shadow",
  "Greater Spire",
  "Greater Spire Shadow",
  "Defiler Mound",
  "Defiler Mound Shadow",
  "Queen's Nest",
  "Queen Nest Shadow",
  "Nydus Canal",
  "Nydus Canal Shadow",
  "Overmind With Shell",
  "Overmind Remnants",
  "Overmind Without Shell",
  "Ultralisk Cavern",
  "Ultralisk Cavern Shadow",
  "Extractor",
  "Extractor Shadow",
  "Hydralisk Den",
  "Hydralisk Den Shadow",
  "Spire",
  "Spire Shadow",
  "Spore Colony",
  "Spore Colony Shadow",
  "Infested Command Center Overlay",
  "Zerg Construction (Large)",
  "Zerg Building Morph",
  "Zerg Construction (Medium)",
  "Zerg Construction (Small)",
  "Zerg Building Construction Shadow",
  "Zerg Building Spawn (Small)",
  "Zerg Building Spawn (Medium)",
  "Zerg Building Spawn (Large)",
  "Zerg Building Rubble (Small)",
  "Zerg Building Rubble (Large)",
  "Carrier",
  "Carrier Shadow",
  "Carrier Engines",
  "Carrier Warp Flash",
  "Interceptor",
  "Interceptor Shadow",
  "Shuttle",
  "Shuttle Shadow",
  "Shuttle Engines",
  "Shuttle Warp Flash",
  "Dragoon",
  "Dragoon Shadow",
  "Dragoon Remnants",
  "Dragoon Warp Flash",
  "High Templar",
  "High Templar Shadow",
  "High Templar Warp Flash",
  "Dark Templar (Hero)",
  "Arbiter",
  "Arbiter Shadow",
  "Arbiter Engines",
  "Arbiter Warp Flash",
  "Archon Energy",
  "Archon Being",
  "Archon Swirl",
  "Probe",
  "Probe Shadow",
  "Probe Warp Flash",
  "Scout",
  "Scout Shadow",
  "Scout Engines",
  "Scout Warp Flash",
  "Reaver",
  "Reaver Shadow",
  "Reaver Warp Flash",
  "Scarab",
  "Observer",
  "Observer Shadow",
  "Observer Warp Flash",
  "Zealot",
  "Zealot Shadow",
  "Zealot Death",
  "Zealot Warp Flash",
  "Templar Archives",
  "Templar Archives Warp Flash",
  "Templar Archives Shadow",
  "Assimilator",
  "Assimilator Warp Flash",
  "Assimilator Shadow",
  "Observatory",
  "Observatory Warp Flash",
  "Observatory Shadow",
  "Citadel of Adun",
  "Citadel of Adun Warp Flash",
  "Citadel of Adun Shadow",
  "Forge",
  "Forge Overlay",
  "Forge Warp Flash",
  "Forge Shadow",
  "Gateway",
  "Gateway Warp Flash",
  "Gateway Shadow",
  "Cybernetics Core",
  "Cybernetics Core Warp Flash",
  "Cybernetics Core Overlay",
  "Cybernetics Core Shadow",
  "Khaydarin Crystal Formation",
  "Nexus",
  "Nexus Warp Flash",
  "Nexus Overlay",
  "Nexus Shadow",
  "Photon Cannon",
  "Photon Cannon Shadow",
  "Photon Cannon Warp Flash",
  "Arbiter Tribunal",
  "Arbiter Tribunal Warp Flash",
  "Arbiter Tribunal Shadow",
  "Pylon",
  "Pylon Warp Flash",
  "Pylon Shadow",
  "Robotics Facility",
  "Robotics Facility Warp Flash",
  "Robotics Facility Shadow",
  "Shield Battery",
  "Shield Battery Overlay",
  "Shileld Battery Warp Flash",
  "Shield Battery Shadow",
  "Stargate",
  "Stargate Overlay",
  "Stargate Warp Flash",
  "Stargate Shadow",
  "Stasis Cell/Prison",
  "Robotics Support Bay",
  "Robotics Support Bay Warp Flash",
  "Robotics Support Bay Shadow",
  "Protoss Temple",
  "Fleet Beacon",
  "Fleet Beacon Warp Flash",
  "Warp Texture",
  "Warp Anchor",
  "Fleet Beacon Shadow",
  "Explosion1 (Small)",
  "Explosion1 (Medium)",
  "Explosion (Large)",
  "Protoss Building Rubble (Small)",
  "Protoss Building Rubble (Large)",
  "Battlecruiser",
  "Battlecruiser Shadow",
  "Battlecruiser Engines",
  "Civilian",
  "Civilian Shadow",
  "Dropship",
  "Dropship Shadow",
  "Dropship Engines",
  "Firebat",
  "Firebat Shadow",
  "Ghost",
  "Ghost Shadow",
  "Ghost Remnants",
  "Ghost Death",
  "Nuke Beam",
  "Nuke Target Dot",
  "Goliath Base",
  "Goliath Turret",
  "Goliath Shadow",
  "Sarah Kerrigan",
  "Sarah Kerrigan Shadow",
  "Marine",
  "Marine Shadow",
  "Marine Remnants",
  "Marine Death",
  "Wraith",
  "Wraith Shadow",
  "Wraith Engines",
  "Scanner Sweep",
  "SCV",
  "SCV Shadow",
  "SCV Glow",
  "Siege Tank (Tank) Base",
  "Siege Tank (Tank) Turret",
  "Siege Tank (Tank) Base Shadow",
  "Siege Tank (Siege) Base",
  "Siege Tank (Siege) Turret",
  "Siege Tank (Siege) Base Shadow",
  "Vulture",
  "Vulture Shadow",
  "Spider Mine",
  "Spider Mine Shadow",
  "Science Vessel (Base)",
  "Science Vessel (Turret)",
  "Science Vessel Shadow",
  "Terran Academy",
  "Academy Overlay",
  "Academy Shadow",
  "Barracks",
  "Barracks Shadow",
  "Armory",
  "Armory Overlay",
  "Armory Shadow",
  "Comsat Station",
  "Comsat Station Connector",
  "Comsat Station Overlay",
  "Comsat Station Shadow",
  "Command Center",
  "Command Center Overlay",
  "Command Center Shadow",
  "Supply Depot",
  "Supply Depot Overlay",
  "Supply Depot Shadow",
  "Control Tower",
  "Control Tower Connector",
  "Control Tower Overlay",
  "Control Tower Shadow",
  "Factory",
  "Factory Overlay",
  "Factory Shadow",
  "Covert Ops",
  "Covert Ops Connector",
  "Covert Ops Overlay",
  "Covert Ops Shadow",
  "Ion Cannon",
  "Machine Shop",
  "Machine Shop Connector",
  "Machine Shop Shadow",
  "Missile Turret (Base)",
  "Missile Turret (Turret)",
  "Missile Turret (Base) Shadow",
  "Crashed Batlecruiser",
  "Crashed Battlecruiser Shadow",
  "Physics Lab",
  "Physics Lab Connector",
  "Physics Lab Shadow",
  "Bunker",
  "Bunker Shadow",
  "Bunker Overlay",
  "Refinery",
  "Refinery Shadow",
  "Science Facility",
  "Science Facility Overlay",
  "Science Facility Shadow",
  "Nuclear Silo",
  "Nuclear Silo Connector",
  "Nuclear Silo Overlay",
  "Nuclear Silo Shadow",
  "Nuclear Missile",
  "Nuclear Missile Shadow",
  "Nuke Hit",
  "Starport",
  "Starport Overlay",
  "Starport Shadow",
  "Engineering Bay",
  "Engineering Bay Overlay",
  "Engineering Bay Shadow",
  "Terran Construction (Large)",
  "Terran Construction (Large) Shadow",
  "Terran Construction (Medium)",
  "Terran Construction (Medium) Shadow",
  "Addon Construction",
  "Terran Construction (Small)",
  "Terran Construction (Small) Shadow",
  "Explosion2 (Small)",
  "Explosion2 (Medium)",
  "Building Explosion (Large)",
  "Terran Building Rubble (Small)",
  "Terran Building Rubble (Large)",
  "Dark Swarm",
  "Ragnasaur (Ash)",
  "Ragnasaur (Ash) Shadow",
  "Rhynadon (Badlands)",
  "Rhynadon (Badlands) Shadow",
  "Bengalaas (Jungle)",
  "Bengalaas (Jungle) Shadow",
  "Vespene Geyser",
  "Vespene Geyser2",
  "Vespene Geyser Shadow",
  "Mineral Field Type1",
  "Mineral Field Type1 Shadow",
  "Mineral Field Type2",
  "Mineral Field Type2 Shadow",
  "Mineral Field Type3",
  "Mineral Field Type3 Shadow",
  "Independent Starport (Unused)",
  "Zerg Beacon",
  "Zerg Beacon Overlay",
  "Terran Beacon",
  "Terran Beacon Overlay",
  "Protoss Beacon",
  "Protoss Beacon Overlay",
  "Unknown360",
  "Lockdown Field (Small)",
  "Lockdown Field (Medium)",
  "Lockdown Field (Large)",
  "Stasis Field Hit",
  "Stasis Field (Small)",
  "Stasis Field (Medium)",
  "Stasis Field (Large)",
  "Recharge Shields (Small)",
  "Recharge Shields (Medium)",
  "Recharge Shields (Large)",
  "Defensive Matrix Front (Small)",
  "Defensive Matrix Front (Medium)",
  "Defensive Matrix Front (Large)",
  "Defensive Matrix Back (Small)",
  "Defensive Matrix Back (Medium)",
  "Defensive Matrix Back (Large)",
  "Defensive Matrix Hit (Small)",
  "Defensive Matrix Hit (Medium)",
  "Defensive Matrix Hit (Large)",
  "Irradiate (Small)",
  "Irradiate (Medium)",
  "Irradiate (Large)",
  "Ensnare Cloud",
  "Ensnare Overlay (Small)",
  "Ensnare Overlay (Medium)",
  "Ensnare Overlay (Large)",
  "Plague Cloud",
  "Plague Overlay (Small)",
  "Plague Overlay (Medium)",
  "Plague Overlay (Large)",
  "Recall Field",
  "Flag",
  "Young Chrysalis",
  "Psi Emitter",
  "Data Disc",
  "Khaydarin Crystal",
  "Mineral Chunk Type1",
  "Mineral Chunk Type2",
  "Protoss Gas Orb Type1",
  "Protoss Gas Orb Type2",
  "Zerg Gas Sac Type1",
  "Zerg Gas Sac Type2",
  "Terran Gas Tank Type1",
  "Terran Gas Tank Type2",
  "Mineral Chunk Shadow",
  "Protoss Gas Orb Shadow",
  "Zerg Gas Sac Shadow",
  "Terran Gas Tank Shadow",
  "Data Disk Shadow (Ground)",
  "Data Disk Shadow (Carried)",
  "Flag Shadow (Ground)",
  "Flag Shadow (Carried)",
  "Crystal Shadow (Ground)",
  "Crystal Shadow (Carried)",
  "Young Chrysalis Shadow (Ground)",
  "Young Chrysalis Shadow (Carried)",
  "Psi Emitter Shadow (Ground)",
  "Psi Emitter Shadow (Carried)",
  "Acid Spray (Unused)",
  "Unknown420",
  "FlameThrower",
  "Longbolt/Gemini Missiles Trail",
  "Burrowing Dust",
  "Shield Overlay",
  "Unknown425",
  "Double Explosion",
  "Phase Disruptor Hit",
  "Nuclear Missile Death",
  "Spider Mine Death",
  "Vespene Geyser Smoke1",
  "Vespene Geyser Smoke2",
  "Vespene Geyser Smoke3",
  "Vespene Geyser Smoke4",
  "Vespene Geyser Smoke5",
  "Unknown435",
  "Unknown436",
  "Unknown437",
  "Unknown438",
  "Unknown439",
  "Fragmentation Grenade Hit",
  "Grenade Shot Smoke",
  "Anti-Matter Missile Hit",
  "Scarab/Anti-Matter Missile Overlay",
  "Scarab Hit",
  "Cursor Marker",
  "Battlecruiser Attack Overlay",
  "Burst Lasers Hit",
  "Unknown448",
  "High Templar Glow",
  "Flames1 Type1 (Small)",
  "Flames1 Type2 (Small)",
  "Flames1 Type3 (Small)",
  "Flames2 Type3 (Small)",
  "Flames3 Type3 (Small)",
  "Flames4 Type3 (Small)",
  "Flames5 Type3 (Small)",
  "Flames6 Type3 (Small)",
  "Bleeding Variant1 Type1 (Small)",
  "Bleeding Variant1 Type2 (Small)",
  "Bleeding Variant1 Type3 (Small)",
  "Bleeding Variant1 Type4 (Small)",
  "Bleeding Variant2 Type1 (Small)",
  "Bleeding Variant2 Type2 (Small)",
  "Bleeding Variant2 Type3 (Small)",
  "Bleeding Variant2 Type4 (Small)",
  "Flames2 Type1 (Small)",
  "Flames2 Type2 (Small)",
  "Flames7 Type3 (Small)",
  "Flames3 Type1 (Small)",
  "Flames3 Type2 (Small)",
  "Flames8 Type3 (Small)",
  "Flames1 Type1 (Large)",
  "Flames1 Type2 (Large)",
  "Flames1 Type3 (Large)",
  "Flames2 Type3 (Large)",
  "Flames3 Type3 (Large)",
  "Flames4 Type3 (Large)",
  "Flames5 Type3 (Large)",
  "Flames6 Type3 (Large)",
  "Bleeding Variant1 Type1 (Large)",
  "Bleeding Variant1 Type2 (Large)",
  "Bleeding Variant1 Type3 (Large)",
  "Bleeding Variant1 Type4 (Large)",
  "Bleeding Variant2 Type1 (Large)",
  "Bleeding Variant2 Type3 (Large)",
  "Bleeding Variant3 Type3 (Large)",
  "Bleeding Variant2 Type4 (Large)",
  "Flames2 Type1 (Large)",
  "Flames2 Type2 (Large)",
  "Flames7 Type3 (Large)",
  "Flames3 Type1 (Large)",
  "Flames3 Type2 (Large)",
  "Flames8 Type3 (Large)",
  "Building Landing Dust Type1",
  "Building Landing Dust Type2",
  "Building Landing Dust Type3",
  "Building Landing Dust Type4",
  "Building Landing Dust Type5",
  "Building Lifting Dust Type1",
  "Building Lifting Dust Type2",
  "Building Lifting Dust Type3",
  "Building Lifting Dust Type4",
  "White Circle",
  "Needle Spine Hit",
  "Unknown505",
  "Sunken Colony Tentacle",
  "Venom (Unused Zerg Weapon)",
  "Venom Hit (Unused)",
  "Acid Spore",
  "Acid Spore Hit",
  "Glave Wurm",
  "Glave Wurm/Seeker Spores Hit",
  "Glave Wurm Trail",
  "Seeker Spores Overlay",
  "Seeker Spores",
  "Queen Spell Holder",
  "Consume",
  "Guardian Attack Overlay",
  "Dual Photon Blasters Hit",
  "Particle Beam Hit",
  "Anti-Matter Missile",
  "Pulse Cannon",
  "Phase Disruptor",
  "STA/STS Photon Cannon Overlay",
  "Psionic Storm",
  "Fusion Cutter Hit",
  "Gauss Rifle Hit",
  "Gemini Missiles",
  "Lockdown/LongBolt/Hellfire Missile",
  "Gemini Missiles Explosion",
  "C-10 Canister Rifle Hit",
  "Fragmentation Grenade",
  "Arclite Shock Cannon Hit",
  "ATS/ATA Laser Battery",
  "Burst Lasers",
  "Siege Tank(Tank) Turret Attack Overlay",
  "Siege Tank(Siege) Turret Attack Overlay",
  "Science Vessel Overlay (Part1)",
  "Science Vessel Overlay (Part2)",
  "Science Vessel Overlay (Part3)",
  "Yamato Gun",
  "Yamato Gun Trail",
  "Yamato Gun Overlay",
  "Yamato Gun Hit",
  "Hallucination Hit",
  "Scanner Sweep Hit",
  "Unknown547",
  "Psionic Shockwave Hit",
  "Archon Beam",
  "Psionic Storm Part1",
  "Psionic Storm Part2",
  "Psionic Storm Part3",
  "Psionic Storm Part4",
  "EMP Shockwave Missile",
  "EMP Shockwave Hit (Part1)",
  "EMP Shockwave Hit (Part2)",
  "Hallucination Death1",
  "Hallucination Death2",
  "Hallucination Death3",
  "Circle Marker1",
  "Selection Circle (22pixels)",
  "Selection Circle (32pixels)",
  "Selection Circle (48pixels)",
  "Selection Circle (62pixels)",
  "Selection Circle (72pixels)",
  "Selection Circle (94pixels)",
  "Selection Circle (110pixels)",
  "Selection Circle (122pixels)",
  "Selection Circle (146pixels)",
  "Selection Circle (224pixels)",
  "Selection Circle Dashed (22pixels)",
  "Selection Circle Dashed (32pixels)",
  "Selection Circle Dashed (48pixels)",
  "Selection Circle Dashed (62pixels)",
  "Selection Circle Dashed (72pixels)",
  "Selection Circle Dashed (94pixels)",
  "Selection Circle Dashed (110pixels)",
  "Selection Circle Dashed (122pixels)",
  "Selection Circle Dashed (146pixels)",
  "Selection Circle Dashed (224pixels)",
  "Circle Marker2",
  "Map Revealer",
  "Circle Marker3",
  "Psi Field1 (Right Upper)",
  "Psi Field1 (Right Lower)",
  "Psi Field2 (Right Upper)",
  "Psi Field2 (Right Lower)",
  "Start Location",
  "2/38 Ash",
  "2/38 Ash Shadow",
  "2/39 Ash",
  "2/39 Ash Shadow",
  "2/41 Ash",
  "2/41 Ash Shadow",
  "2/40 Ash",
  "2/40 Ash Shadow",
  "2/42 Ash",
  "2/42 Ash Shadow",
  "2/43 Ash",
  "2/44 Ash ",
  "2/1 Ash",
  "2/4 Ash",
  "2/5 Ash",
  "2/30 Ash",
  "2/28 Ash",
  "2/29 Ash",
  "4/1 Ash ",
  "4/2 Ash",
  "4/3 Ash",
  "4/56 Jungle",
  "4/56 Jungle Shadow",
  "4/57 Jungle",
  "4/57 Jungle Shadow",
  "4/58 Jungle",
  "4/58 Jungle Shadow",
  "4/59 Jungle",
  "4/59 Jungle Shadow",
  "9/5 Jungle",
  "9/5 Jungle Shadow",
  "9/6 Jungle",
  "9/6 Jungle Shadow",
  "9/7 Jungle",
  "9/7 Jungle Shadow",
  "4/51 Jungle",
  "4/51 Jungle Shadow",
  "4/52 Jungle",
  "4/52 Jungle Shadow",
  "4/54 Jungle",
  "4/54 Jungle Shadow",
  "4/53 Jungle",
  "4/53 Jungle Shadow",
  "9/1 Jungle",
  "9/1 Jungle Shadow",
  "9/2 Jungle",
  "9/2 Jungle Shadow",
  "9/3 Jungle",
  "9/3 Jungle Shadow",
  "9/4 Jungle",
  "9/4 Jungle Shadow",
  "4/12 Jungle",
  "4/13 Jungle",
  "4/1 Jungle",
  "4/3 Jungle",
  "4/2 Jungle",
  "4/5 Jungle",
  "4/4 Jungle",
  "4/9 Jungle",
  "4/10 Jungle",
  "5/5 Jungle",
  "5/7 Jungle",
  "5/6 Jungle",
  "5/9 Jungle",
  "5/8 Jungle",
  "4/6 Jungle",
  "4/7 Jungle",
  "4/17 Jungle",
  "13/4 Jungle",
  "11/5 Jungle",
  "11/6 Jungle",
  "11/7 Jungle",
  "11/8 Jungle",
  "11/10 Jungle",
  "11/11 Jungle",
  "11/12 Jungle",
  "7/4 Platform",
  "7/4 Platform Shadow",
  "7/5 Platform",
  "7/5 Platform Shadow",
  "7/6 Platform",
  "7/6 Platform Shadow",
  "7/1 Platform",
  "7/1 Platform Shadow",
  "7/2 Platform",
  "7/2 Platform Shadow",
  "7/3 Platform",
  "7/3 Platform Shadow",
  "7/9 Platform",
  "7/10 Platform",
  "7/8 Platform",
  "7/7 Platform",
  "7/26 Platform",
  "7/24 Platform",
  "7/28 Platform",
  "7/27 Platform",
  "7/25 Platform",
  "7/29 Platform",
  "7/30 Platform",
  "7/31 Platform",
  "12/1 Platform",
  "9/27 Platform",
  "5/54 Badlands",
  "5/54 Badlands Shadow",
  "5/55 Badlands",
  "5/55 Badlands Shadow",
  "5/56 Badlands",
  "5/56 Badlands Shadow",
  "5/57 Badlands",
  "5/57 Badlands Shadow",
  "6/16 Badlands",
  "6/17 Badlands",
  "6/20 Badlands",
  "6/21 Badlands",
  "5/10 Badlands",
  "5/50 Badlands",
  "5/50 Badlands Shadow",
  "5/52 Badlands",
  "5/52 Badlands Shadow",
  "5/53 Badlands",
  "5/53 Badlands Shadow",
  "5/51 Badlands",
  "5/51 Badlands Shadow",
  "6/3 Badlands",
  "11/3 Badlands",
  "11/8 Badlands",
  "11/6 Badlands",
  "11/7 Badlands",
  "11/9 Badlands",
  "11/10 Badlands",
  "11/11 Badlands",
  "11/12 Badlands",
  "11/13 Badlands",
  "11/14 Badlands",
  "1/13 Badlands",
  "1/9 Badlands",
  "1/11 Badlands",
  "1/14 Badlands",
  "1/10 Badlands",
  "1/12 Badlands",
  "1/15 Badlands",
  "1/7 Badlands",
  "1/5 Badlands",
  "1/16 Badlands",
  "1/8 Badlands",
  "1/6 Badlands",
  "Floor Gun Trap",
  "Floor Missile Trap",
  "Floor Missile Trap Turret",
  "Wall Missile Trap",
  "Wall Missile Trap2",
  "Wall Flame Trap",
  "Wall Flame Trap2",
  "Left Upper Level Door",
  "Right Upper Level Door",
  "4/15 Installation1",
  "4/15 Installation2",
  "3/9 Installation",
  "3/10 Installation",
  "3/11 Installation",
  "3/12 Installation",
  "Substructure Left Door",
  "Substructure Right Door",
  "3/1 Installation",
  "3/2 Installation",
  "Substructure Opening Hole",
  "7/21 Twilight",
  "Unknown Twilight",
  "7/13 Twilight",
  "7/14 Twilight",
  "7/16 Twilight",
  "7/15 Twilight",
  "7/19 Twilight",
  "7/20 Twilight",
  "7/17 Twilight",
  "6/1 Twilight",
  "6/2 Twilight",
  "6/3 Twilight",
  "6/4 Twilight",
  "6/5 Twilight",
  "8/3 Twilight1",
  "8/3 Twilight2",
  "9/29 Ice",
  "9/29 Ice Shadow",
  "9/28 Ice",
  "9/28 Ice Shadow",
  "12/38 Ice ",
  "12/38 Ice Shadow",
  "12/37 Ice",
  "12/37 Ice Shadow",
  "12/33 Ice1",
  "12/33 Ice1 Shadow",
  "9/21 Ice",
  "9/21 Ice Shadow",
  "9/15 Ice",
  "9/15 Ice Shadow",
  "9/16 Ice",
  "9/16 Ice Shadow",
  "Unknown787",
  "Unknown788",
  "12/9 Ice1",
  "12/10 Ice1",
  "9/24 Ice",
  "9/24 Ice Shadow",
  "9/23 Ice",
  "9/23 Ice Shadow",
  "Unknown795",
  "Unknown Ice Shadow",
  "12/7 Ice",
  "12/7 Ice Shadow",
  "12/8 Ice",
  "12/8 Ice Shadow",
  "12/9 Ice2",
  "12/9 Ice2 Shadow",
  "12/10 Ice2",
  "12/10 Ice2 Shadow",
  "12/40 Ice",
  "12/40 Ice Shadow",
  "12/41 Ice",
  "12/41 Ice Shadow",
  "12/42 Ice",
  "12/42 Ice Shadow",
  "12/5 Ice",
  "12/5 Ice Shadow",
  "12/6 Ice",
  "12/6 Ice Shadow",
  "12/36 Ice",
  "12/36 Ice Shadow",
  "12/32 Ice",
  "12/32 Ice Shadow",
  "12/33 Ice2",
  "12/33 Ice2 Shadow",
  "12/34 Ice",
  "12/34 Ice Shadow",
  "12/24 Ice1",
  "12/24 Ice1 Shadow",
  "12/25 Ice1",
  "12/25 Ice1 Shadow",
  "12/30 Ice1",
  "12/30 Ice1 Shadow",
  "12/31 Ice",
  "12/31 Ice Shadow",
  "12/20 Ice",
  "12/30 Ice2",
  "12/30 Ice2 Shadow",
  "9/22 Ice",
  "9/22 Ice Shadow",
  "12/24 Ice2",
  "12/24 Ice2 Shadow",
  "12/25 Ice2",
  "12/25 Ice2 Shadow",
  "Unknown840",
  "4/1 Ice",
  "6/1 Ice",
  "5/6 Ice ",
  "5/6 Ice Shadow",
  "5/7 Ice ",
  "5/7 Ice Shadow",
  "5/8 Ice ",
  "5/8 Ice Shadow",
  "5/9 Ice",
  "5/9 Ice Shadow",
  "10/10 Desert1",
  "10/12 Desert1",
  "10/12 Desert1 Shadow",
  "10/8 Desert1",
  "10/8 Desert1 Shadow",
  "10/9 Desert1",
  "10/9 Desert1 Shadow",
  "6/10 Desert",
  "6/10 Desert Shadow",
  "6/13 Desert1",
  "6/13 Desert1 Shadow",
  "Unknown Desert",
  "Unknown Desert Shadow",
  "10/12 Desert2",
  "10/12 Desert2 Shadow",
  "10/9 Desert2",
  "10/9 Desert2 Shadow",
  "10/10 Desert2",
  "10/10 Desert2 Shadow",
  "10/11 Desert",
  "10/11 Desert Shadow",
  "10/14 Desert",
  "10/14 Desert Shadow",
  "10/41 Desert",
  "10/41 Desert Shadow",
  "10/39 Desert",
  "1/39 Desert Shadow",
  "10/8 Desert2",
  "10/8 Desert2 Shadow",
  "10/6 Desert",
  "10/7 Desert",
  "10/7 Desert Shadow",
  "4/6 Desert",
  "4/6 Desert Shadow",
  "4/11 Desert",
  "4/11 Desert Shadow",
  "4/10 Desert",
  "4/10 Desert Shadow",
  "4/9 Desert",
  "4/7 Desert",
  "4/7 Desert Shadow",
  "4/12 Desert",
  "4/12 Desert Shadow",
  "4/8 Desert",
  "4/13 Desert",
  "4/13 Desert Shadow",
  "4/17 Desert",
  "4/15 Desert1",
  "4/15 Desert1 Shadow",
  "10/23 Desert",
  "10/23 Desert Shadow",
  "10/5 Desert",
  "10/5 Desert Shadow",
  "6/13 Desert2",
  "6/13 Desert2 Shadow",
  "6/20 Desert",
  "4/15 Desert2",
  "4/15 Desert2 Shadow",
  "8/23 Desert",
  "8/23 Desert Shadow",
  "12/1 Desert Overlay",
  "11/3 Desert",
  "Unknown913",
  "Lurker Egg",
  "Devourer",
  "Devourer Shadow",
  "Devourer Birth",
  "Devourer Death",
  "Lurker Birth",
  "Lurker Remnants",
  "Lurker",
  "Lurker Shadow",
  "Overmind Cocoon",
  "Overmind Cocoon Shadow",
  "Dark Archon Energy",
  "Dark Archon Being",
  "Dark Archon Swirl",
  "Dark Archon Death",
  "Corsair",
  "Corsair Shadow",
  "Corsair Engines",
  "Corsair Attack Overlay (Unused)",
  "Dark Templar (Unit)",
  "Warp Gate",
  "Warp Gate Shadow",
  "Warp Gate Overlay",
  "Xel'Naga Temple",
  "Xel'Naga Temple Shadow",
  "Valkyrie",
  "Valkyrie Shadow",
  "Valkyrie Engines",
  "Valkyrie Engines2 (Unused)",
  "Valkyrie Afterburners (Unused)",
  "Medic",
  "Medic Shadow",
  "Medic Remnants",
  "Psi Disrupter",
  "Psi Disrupter Shadow",
  "Power Generator",
  "Power Generator Shadow",
  "Disruption Web",
  "Scantid (Desert)",
  "Scantid (Desert) Shadow",
  "Kakaru (Twilight)",
  "Kakaru (Twilight) Shadow",
  "Ursadon (Ice)",
  "Ursadon (Ice) Shadow",
  "Uraj",
  "Khalis",
  "Halo Rockets Trail",
  "Subterranean Spines",
  "Coroosive Acid Shot",
  "Corrosive Acid Hit",
  "Neutron Flare",
  "Halo Rockets",
  "Optical Flare Grenade",
  "Restoration Hit (Small)",
  "Restoration Hit (Medium)",
  "Restoration Hit (Large)",
  "Heal (Small)",
  "Heal (medium)",
  "Heal (Large)",
  "Mind Control Hit (Small)",
  "Mind Control Hit (Medium)",
  "Mind Control Hit (Large)",
  "Optical Flare Hit (Small)",
  "Optical Flare Hit (Medium)",
  "Optical Flare Hit (Large)",
  "Feedback (Small)",
  "Feedback (Medium)",
  "Feedback Hit (Large)",
  "Maelstorm Overlay (Small)",
  "Maelstorm Overlay (Medium)",
  "Maelstorm Overlay (Large)",
  "Unknown985",
  "Acid Spores (1) Overlay (Small)",
  "Acid Spores (2-3) Overlay (Small)",
  "Acid Spores (4-5) Overlay (Small)",
  "Acid Spores (6-9) Overlay (Small)",
  "Acid Spores (1) Overlay (Medium)",
  "Acid Spores (2-3) Overlay (Medium)",
  "Acid Spores (4-5) Overlay (Medium)",
  "Acid Spores (6-9) Overlay (Medium)",
  "Acid Spores (1) Overlay (Large)",
  "Acid Spores (2-3) Overlay (Large)",
  "Acid Spores (4-5) Overlay (Large)",
  "Acid Spores (6-9) Overlay (Large)",
  "Maelstorm Hit",
];

export const SCIscript = [
  "Scourge",
  "Unknown1",
  "Scourge Death",
  "Scourge Explosion",
  "Broodling",
  "Broodling Remnants",
  "Infested Terran",
  "Infested Terran Explosion",
  "Guardian Cocoon",
  "Defiler",
  "Defiler Remnants",
  "Drone",
  "Drone Remnants",
  "Egg",
  "Egg Remnants",
  "Guardian",
  "Guardian Birth",
  "Guardian Death",
  "Hydralisk",
  "Hydralisk Remnants",
  "Infested Kerrigan",
  "Larva",
  "Larva Remnants",
  "Mutalisk",
  "Mutalisk Death",
  "Overlord",
  "Overlord Death",
  "Queen",
  "Queen Death",
  "Ultralisk",
  "Ultralisk Remnants",
  "Zergling",
  "Zergling Remnants",
  "Zerg Air Death Explosion",
  "Zerg Building Explosion",
  "Unknown35",
  "Zerg Birth",
  "Egg Spawn",
  "Cerebrate",
  "Infested Command Center",
  "Spawning Pool",
  "Evolution Chamber",
  "Creep Colony",
  "Hatchery",
  "Hive",
  "Lair",
  "Sunken Colony",
  "Mature Chrysalis",
  "Greater Spire",
  "Defiler Mound",
  "Queen Nest",
  "Nydus Canal",
  "Overmind(with Shell)",
  "Overmind Remnants",
  "Overmind(without Shell)",
  "Ultralisk Cavern",
  "Extractor",
  "Hydralisk Den",
  "Spire",
  "Spore Colony",
  "Infested Command Center Overlay",
  "Zerg Construction(Small)",
  "Zerg Construction(Medium)",
  "Zerg Building Morph",
  "Zerg Construction(Large)",
  "Zerg Building Spawn",
  "Battlecruiser",
  "Civilian",
  "Dropship",
  "Firebat",
  "Ghost",
  "Ghost Remnants",
  "Ghost Death",
  "Nuke Beam",
  "Nuke Target Dot",
  "Goliath(Base)",
  "Goliath(Turret)",
  "Sarah Kerrigan",
  "Marine",
  "Marine Remnants",
  "Marine Death",
  "Scanner Sweep",
  "Wraith",
  "Wraith Afterburners",
  "SCV",
  "Unknown85",
  "Vulture",
  "Spider Mine",
  "Science Vessel(Base)",
  "Science Vessel(Turret)",
  "Siege Tank(Tank) Base",
  "Siege Tank(Tank) Turret",
  "Siege Tank(Siege) Base",
  "Siege Tank(Siege) Turret",
  "Academy",
  "Academy Overlay",
  "Barracks",
  "Armory",
  "Armory Overlay",
  "Comsat Station",
  "Comsat Connector",
  "Comsat Overlay",
  "Command Center",
  "Command Center Overlay",
  "Crashed Battlecruiser",
  "Supply Depot",
  "Supply Depot Overlay",
  "Control Tower",
  "Control Tower Connector",
  "Control Tower Overlay",
  "Unknown110",
  "Factory",
  "Factory Overlay",
  "Covert Ops",
  "Covert Ops Connector",
  "Covert Ops Overlay",
  "Ion Cannon",
  "Machine Shop",
  "Machine Shop Connector",
  "Missile Turret(Base)",
  "Missile Turret(Turret)",
  "Physics Lab",
  "Physics Lab Connector",
  "Bunker",
  "Bunker Overlay",
  "Refinery",
  "Science Facility",
  "Science Facility Overlay",
  "Nuclear Silo",
  "Nuclear Silo Connector",
  "Nuclear Silo Overlay",
  "Nuclear Missile",
  "Unknown132",
  "Nuke Explosion",
  "Starport",
  "Starport Overlay",
  "Engineering Bay",
  "Engineering Bay Overlay",
  "Terran Construction(Large)",
  "Terran Construction(Medium)",
  "Terran Construction(Small)",
  "Addon Construction",
  "Explosion(Small)",
  "Explosion(Medium)",
  "Explosion(Large)",
  "Building Rubble Header",
  "Arbiter",
  "Archon Energy",
  "Archon Being",
  "Archon Swirl",
  "Unknown150",
  "Carrier",
  "Dark Templar(Hero)",
  "Dragoon",
  "Dragoon Remnants",
  "Interceptor",
  "Probe",
  "Shuttle",
  "High Templar",
  "Reaver",
  "Scarab",
  "Scout",
  "Scout Engines",
  "Zealot",
  "Zealot Death",
  "Observer",
  "Templar Archives",
  "Assimilator",
  "Observatory",
  "Unknown169",
  "Citadel Of Adun",
  "Forge",
  "Forge Overlay",
  "Gateway",
  "Cybernetics Core",
  "Cybrnetics Core Overlay",
  "Khaydarin Crystal Formation",
  "Nexus",
  "Nexus Overlay",
  "Photon Cannon",
  "Arbiter Tribunal",
  "Pylon",
  "Robotics Facility",
  "Shield Battery",
  "Shield Battery Overlay",
  "Stargate",
  "Stargate Overlay",
  "Stasis Cell/Prison",
  "Robotics Support Bay",
  "Temple",
  "Fleet Beacon",
  "Warp Anchor",
  "Warp Flash Header",
  "Warp Texture",
  "Unknown194",
  "Unknown195",
  "Unknown196",
  "Unknown197",
  "Ragnasaur(Ashworld Critter)",
  "Rhynadon(Badlands Critter)",
  "Bengalaas(Jungle Critter)",
  "Vespene Geyser",
  "Vespene Geyser2",
  "Vespene Geyser Shadow",
  "Mineral Field Type1",
  "Mineral Field Type2",
  "Mineral Field Type3",
  "Unknown207",
  "Zerg Beacon Overlay",
  "Terran Beacon Overlay",
  "Protoss Beacon Overlay",
  "Zerg Beacon",
  "Protoss Beacon",
  "Terran Beacon",
  "Unknwon214",
  "Powerups Shadow Header",
  "Flag",
  "Psi Emitter",
  "Data Disk",
  "Crystals Shadows",
  "Young Chrysalis",
  "Ore Chunk",
  "Ore Chunk2",
  "Gas Sac",
  "Gas Sac2",
  "Gas Orb",
  "Gas Orb2",
  "Gas Tank",
  "Gas Tank2",
  "Archon Overlay",
  "Particle Beam Hit",
  "Dual Photon Blaster Hit",
  "Anti-Matter Missile",
  "Pulse Cannon",
  "Phase Disruptor",
  "STA/STS Photon Cannon Overlay",
  "Psionic Storm",
  "Fusion Cutter Hit",
  "Gauss Rifle Hit",
  "Gemini Missiles",
  "Longbolt Missile",
  "C-10 Canister Rifle Hit",
  "Fragmentation Grenade",
  "ATA/ATS Laser Battery/Burst Lasers",
  "Unknown244",
  "Lockdown Hit",
  "Arclite Shock Cannon Hit",
  "Yamato Gun",
  "Yamato Gun Trail",
  "Lockdown/EMP Shockwave Missile",
  "Siege Tank(Tank) Turret Overlay",
  "Siege Tank(Siege) Turret Overlay",
  "Science Vessel Overlay",
  "Hallucination Hit",
  "Unknown254",
  "Unknown255",
  "Needle Spines Hit",
  "Venom (Unused)",
  "Subterranean Tentacle",
  "Venom Hit (Unused)",
  "Acid Spore",
  "Acid Spore Hit",
  "Guardian Attack Overlay",
  "Unknown263",
  "Glave Wurm",
  "Glave Wurm Hit",
  "Seeker Spores",
  "Queen Spell Holder",
  "Psionic Shockwave Hit",
  "Glave Wurm Trail",
  "Seeker Spores Overlay",
  "Acid Spray",
  "Unknown272",
  "Longbolt\\Halo\\Gemini Missiles Trail",
  "Burowing Dust",
  "Shadow Header",
  "Shield Overlay",
  "Unknown277",
  "Double Explosion",
  "Nuclear Missile Death",
  "Spider Mine Explosion",
  "Vespene Geyser Smokes",
  "Unknown282",
  "Fragmentation Grenade Hit",
  "Grenade Shot Smoke",
  "Phase Disruptor/Anti-Matter Missile Hit",
  "Scarab/Anti-Matter Missile Overlay",
  "Scarab Hit",
  "Cursor Marker",
  "Circle Marker",
  "Carrier Engines",
  "Engines/Glow Header",
  "White Circle",
  "Battlecruiser Attack Overlay",
  "ATA/ATS Laser Battery/Burst Lasers Hit",
  "Unknown295",
  "Plague Cloud",
  "Plague Overlay",
  "Consume",
  "Dark Swarm",
  "Defensive Matrix Overlay",
  "Defensive Matrix Hit",
  "Ensnare",
  "Ensnare Overlay",
  "Irradiate",
  "Recall Field",
  "Stasis Field Overlay",
  "Stasis Field Hit",
  "Recharge Shields(Large)",
  "Recharge Shields(Small)",
  "High Templar Glow",
  "Needle Spines Overlay",
  "Flamethrower",
  "Gemini Missiles Explosion",
  "Yamato Gun Overlay",
  "Yamato Gun Hit",
  "Unknown316",
  "Psionic Storm Part Variant1",
  "Psionic Storm Part Variant2",
  "EMP Shockwave Hit(Part1)",
  "EMP Shockwave Hit(Part2)",
  "Hallucination Death",
  "Flames(Small)",
  "Unknown323",
  "Bleeding(Small) Variant1",
  "Bleeding(Small) Variant2",
  "Flames(Large)",
  "Unknown327",
  "Bleeding(Large) Variant1",
  "Bleeding(Large) Variant2",
  "Dust Variant1",
  "Dust Variant2",
  "Confirm Circle",
  "Psi Field Type1",
  "Psi Field Type2",
  "Start Location",
  "Doodad Header",
  "Doodad Header(secondary)",
  "Space Platform Doodad",
  "Space Platform Doodad2",
  "Installation Doodad",
  "Installation Doodad2",
  "Installation Right Wall Fans",
  "Installation Left Wall Fans",
  "Installation Gear",
  "Floor Missile Trap",
  "Floor Missile Trap Turret",
  "Floor Gun Trap",
  "Wall Missile Trap Type1",
  "Wall Missile Trap Typet2",
  "Wall Flame Trap Type1",
  "Wall Flame Trap Type2",
  "Map Revealer",
  "Lurker Egg",
  "Lurker",
  "Unknown355",
  "Lurker Remnants",
  "Devourer",
  "Devourer Birth",
  "Devourer Death",
  "Medic",
  "Medic Remnants",
  "Valkyrie",
  "Unknown363",
  "Unknown364",
  "Dark Archon Energy",
  "Dark Archon Being",
  "Dark Archon Swirl",
  "Dark Archon Death",
  "Corsair",
  "Corsair Engines",
  "Unknown371",
  "Dark Templar(Unit)",
  "Neutron Flare",
  "Disruption Web",
  "Scantid(Desert Critter)",
  "Kakaru(Twilight Critter)",
  "Ursadon(Ice Critter)",
  "Halo Rocket",
  "Optical Flare",
  "Subterranean Spines",
  "Corrosive Acid",
  "Corrosive Acid Hit",
  "Acid Spores (1) Overlay",
  "Acid Spores (2-3) Overlay",
  "Acid Spores (4-5) Overlay",
  "Acid Spores (6-9) Overlay",
  "Ice Doodad",
  "Doodad Shadows Header (BW)",
  "Restoration Hit",
  "Mind Control Hit",
  "Optical Flare Hit",
  "Feedback",
  "Maelstorm Overlay",
  "Unknown394",
  "Unknown395",
  "Desert Doodad",
  "Desert Doodad2",
  "Desert Doodad3",
  "Desert Doodad Overlay",
  "Desert Doodad",
  "Twilight Doodad",
  "Twilight Doodad",
  "Twilight Doodad",
  "Twilight Doodad",
  "Overmind Cocoon",
  "Warp Gate",
  "Psi Disrupter",
  "Power Generator",
  "Warp Gate Overlay",
  "Xel'Naga Temple",
  "Maelstrom Hit",
];
