import { FunctionSymbol } from "../../context/symbolTable/FunctionSymbol";
import { ParameterSymbol } from "../../context/symbolTable/ParameterSymbol";
import { zeroRange } from "../../util/range";

interface BuiltinEncode {
  name: string;
  args: string[];
  doc: string;
}

export const builtinEncode: BuiltinEncode[] = [
  {
    name: "$L",
    args: ["t"],
    doc: "Encode Location Name",
  },
  {
    name: "$U",
    args: ["t"],
    doc: "Encode Unit Name",
  },
  {
    name: "$T",
    args: ["t"],
    doc: "Encode Map String",
  },
  {
    name: "$B",
    args: ["t"],
    doc: "Encode stat_txt.tbl",
  },
  {
    name: "$S",
    args: ["t"],
    doc: "Encode Switch Name",
  },
];

export type SCTrgEncode =
  | "TrgComparison"
  | "TrgModifier"
  | "TrgOrder"
  | "TrgPlayer"
  | "TrgProperty"
  | "TrgResource"
  | "TrgScore"
  | "TrgAIScript"
  | "TrgUnit";

export const SCTrgComparison = ["AtLeast", "AtMost", "Exactly"];

export const SCTrgModifier = ["Add", "SetTo", "Subtract"];

export const SCTrgOrder = ["Attack", "Patrol", "Move"];

export const SCTrgPlayer = [
  "P1",
  "P2",
  "P3",
  "P4",
  "P5",
  "P6",
  "P7",
  "P8",
  "P9",
  "P10",
  "P11",
  "P12",
  "CurrentPlayer",
  "Foes",
  "Allies",
  "NeutralPlayers",
  "Force1",
  "Force2",
  "Force3",
  "Force4",
  "NonAlliesVictoryPlayers",
];

export const SCTrgProperty = [];

export const SCTrgResource = ["Ore", "Gas", "OreAndGas"];

export const SCTrgScore = [
  "Units",
  "Buildings",
  "UnitsAndBuildings",
  "Kills",
  "Razings",
  "KillsAndRazings",
  "Custom",
];

export const SCTrgAIScript = [
  "Terran Custom Level",
  "Zerg Custom Level",
  "Protoss Custom Level",
  "Terran Expansion Custom Level",
  "Zerg Expansion Custom Level",
  "Protoss Expansion Custom Level",
  "Terran Campaign Easy",
  "Terran Campaign Medium",
  "Terran Campaign Difficult",
  "Terran Campaign Insane",
  "Terran Campaign Area Town",
  "Zerg Campaign Easy",
  "Zerg Campaign Medium",
  "Zerg Campaign Difficult",
  "Zerg Campaign Insane",
  "Zerg Campaign Area Town",
  "Protoss Campaign Easy",
  "Protoss Campaign Medium",
  "Protoss Campaign Difficult",
  "Protoss Campaign Insane",
  "Protoss Campaign Area Town",
  "Expansion Terran Campaign Easy",
  "Expansion Terran Campaign Medium",
  "Expansion Terran Campaign Difficult",
  "Expansion Terran Campaign Insane",
  "Expansion Terran Campaign Area Town",
  "Expansion Zerg Campaign Easy",
  "Expansion Zerg Campaign Medium",
  "Expansion Zerg Campaign Difficult",
  "Expansion Zerg Campaign Insane",
  "Expansion Zerg Campaign Area Town",
  "Expansion Protoss Campaign Easy",
  "Expansion Protoss Campaign Medium",
  "Expansion Protoss Campaign Difficult",
  "Expansion Protoss Campaign Insane",
  "Expansion Protoss Campaign Area Town",
  "Send All Units on Strategic Suicide Missions",
  "Send All Units on Random Suicide Missions",
  "Switch Computer Player to Rescue Passive",
  "Turn ON Shared Vision for Player 1",
  "Turn ON Shared Vision for Player 2",
  "Turn ON Shared Vision for Player 3",
  "Turn ON Shared Vision for Player 4",
  "Turn ON Shared Vision for Player 5",
  "Turn ON Shared Vision for Player 6",
  "Turn ON Shared Vision for Player 7",
  "Turn ON Shared Vision for Player 8",
  "Turn OFF Shared Vision for Player 1",
  "Turn OFF Shared Vision for Player 2",
  "Turn OFF Shared Vision for Player 3",
  "Turn OFF Shared Vision for Player 4",
  "Turn OFF Shared Vision for Player 5",
  "Turn OFF Shared Vision for Player 6",
  "Turn OFF Shared Vision for Player 7",
  "Turn OFF Shared Vision for Player 8",
  "Move Dark Templars to Region",
  "Clear Previous Combat Data",
  "Set Player to Enemy",
  "Set Player to Ally  ",
  "Value This Area Higher",
  "Enter Closest Bunker",
  "Set Generic Command Target",
  "Make These Units Patrol",
  "Enter Transport",
  "Exit Transport",
  "AI Nuke Here",
  "AI Harass Here",
  "Set Unit Order To: Junk Yard Dog",
  "Disruption Web Here",
  "Recall Here",
  "Terran 3 - Zerg Town",
  "Terran 5 - Terran Main Town",
  "Terran 5 - Terran Harvest Town",
  "Terran 6 - Air Attack Zerg",
  "Terran 6 - Ground Attack Zerg",
  "Terran 6 - Zerg Support Town",
  "Terran 7 - Bottom Zerg Town",
  "Terran 7 - Right Zerg Town",
  "Terran 7 - Middle Zerg Town",
  "Terran 8 - Confederate Town",
  "Terran 9 - Light Attack",
  "Terran 9 - Heavy Attack",
  "Terran 10 - Confederate Towns",
  "Terran 11 - Zerg Town",
  "Terran 11 - Lower Protoss Town",
  "Terran 11 - Upper Protoss Town",
  "Terran 12 - Nuke Town",
  "Terran 12 - Phoenix Town",
  "Terran 12 - Tank Town",
  "Terran 1 - Electronic Distribution",
  "Terran 2 - Electronic Distribution",
  "Terran 3 - Electronic Distribution",
  "Terran 1 - Shareware",
  "Terran 2 - Shareware",
  "Terran 3 - Shareware",
  "Terran 4 - Shareware",
  "Terran 5 - Shareware",
  "Zerg 1 - Terran Town",
  "Zerg 2 - Protoss Town",
  "Zerg 3 - Terran Town",
  "Zerg 4 - Right Terran Town",
  "Zerg 4 - Lower Terran Town",
  "Zerg 6 - Protoss Town",
  "Zerg 7 - Air Town",
  "Zerg 7 - Ground Town",
  "Zerg 7 - Support Town",
  "Zerg 8 - Scout Town",
  "Zerg 8 - Templar Town",
  "Zerg 9 - Teal Protoss",
  "Zerg 9 - Left Yellow Protoss",
  "Zerg 9 - Right Yellow Protoss",
  "Zerg 9 - Left Orange Protoss",
  "Zerg 9 - Right Orange Protoss",
  "Zerg 10 - Left Teal (Attack",
  "Zerg 10 - Right Teal (Support",
  "Zerg 10 - Left Yellow (Support",
  "Zerg 10 - Right Yellow (Attack",
  "Zerg 10 - Red Protoss",
  "Protoss 1 - Zerg Town",
  "Protoss 2 - Zerg Town",
  "Protoss 3 - Air Zerg Town",
  "Protoss 3 - Ground Zerg Town",
  "Protoss 4 - Zerg Town",
  "Protoss 5 - Zerg Town Island",
  "Protoss 5 - Zerg Town Base",
  "Protoss 7 - Left Protoss Town",
  "Protoss 7 - Right Protoss Town",
  "Protoss 7 - Shrine Protoss",
  "Protoss 8 - Left Protoss Town",
  "Protoss 8 - Right Protoss Town",
  "Protoss 8 - Protoss Defenders",
  "Protoss 9 - Ground Zerg",
  "Protoss 9 - Air Zerg",
  "Protoss 9 - Spell Zerg",
  "Protoss 10 - Mini-Towns",
  "Protoss 10 - Mini-Town Master",
  "Protoss 10 - Overmind Defenders",
  "Brood Wars Protoss 1 - Town A",
  "Brood Wars Protoss 1 - Town ",
  "Brood Wars Protoss 1 - Town C",
  "Brood Wars Protoss 1 - Town D",
  "Brood Wars Protoss 1 - Town E",
  "Brood Wars Protoss 1 - Town F",
  "Brood Wars Protoss 2 - Town A",
  "Brood Wars Protoss 2 - Town ",
  "Brood Wars Protoss 2 - Town C",
  "Brood Wars Protoss 2 - Town D",
  "Brood Wars Protoss 2 - Town E",
  "Brood Wars Protoss 2 - Town F",
  "Brood Wars Protoss 3 - Town A",
  "Brood Wars Protoss 3 - Town ",
  "Brood Wars Protoss 3 - Town C",
  "Brood Wars Protoss 3 - Town D",
  "Brood Wars Protoss 3 - Town E",
  "Brood Wars Protoss 3 - Town F",
  "Brood Wars Protoss 4 - Town A",
  "Brood Wars Protoss 4 - Town ",
  "Brood Wars Protoss 4 - Town C",
  "Brood Wars Protoss 4 - Town D",
  "Brood Wars Protoss 4 - Town E",
  "Brood Wars Protoss 4 - Town F",
  "Brood Wars Protoss 5 - Town A",
  "Brood Wars Protoss 5 - Town ",
  "Brood Wars Protoss 5 - Town C",
  "Brood Wars Protoss 5 - Town D",
  "Brood Wars Protoss 5 - Town E",
  "Brood Wars Protoss 5 - Town F",
  "Brood Wars Protoss 6 - Town A",
  "Brood Wars Protoss 6 - Town ",
  "Brood Wars Protoss 6 - Town C",
  "Brood Wars Protoss 6 - Town D",
  "Brood Wars Protoss 6 - Town E",
  "Brood Wars Protoss 6 - Town F",
  "Brood Wars Protoss 7 - Town A",
  "Brood Wars Protoss 7 - Town ",
  "Brood Wars Protoss 7 - Town C",
  "Brood Wars Protoss 7 - Town D",
  "Brood Wars Protoss 7 - Town E",
  "Brood Wars Protoss 7 - Town F",
  "Brood Wars Protoss 8 - Town A",
  "Brood Wars Protoss 8 - Town ",
  "Brood Wars Protoss 8 - Town C",
  "Brood Wars Protoss 8 - Town D",
  "Brood Wars Protoss 8 - Town E",
  "Brood Wars Protoss 8 - Town F",
  "Brood Wars Terran 1 - Town A",
  "Brood Wars Terran 1 - Town ",
  "Brood Wars Terran 1 - Town C",
  "Brood Wars Terran 1 - Town D",
  "Brood Wars Terran 1 - Town E",
  "Brood Wars Terran 1 - Town F",
  "Brood Wars Terran 2 - Town A",
  "Brood Wars Terran 2 - Town ",
  "Brood Wars Terran 2 - Town C",
  "Brood Wars Terran 2 - Town D",
  "Brood Wars Terran 2 - Town E",
  "Brood Wars Terran 2 - Town F",
  "Brood Wars Terran 3 - Town A",
  "Brood Wars Terran 3 - Town ",
  "Brood Wars Terran 3 - Town C",
  "Brood Wars Terran 3 - Town D",
  "Brood Wars Terran 3 - Town E",
  "Brood Wars Terran 3 - Town F",
  "Brood Wars Terran 4 - Town A",
  "Brood Wars Terran 4 - Town ",
  "Brood Wars Terran 4 - Town C",
  "Brood Wars Terran 4 - Town D",
  "Brood Wars Terran 4 - Town E",
  "Brood Wars Terran 4 - Town F",
  "Brood Wars Terran 5 - Town A",
  "Brood Wars Terran 5 - Town ",
  "Brood Wars Terran 5 - Town C",
  "Brood Wars Terran 5 - Town D",
  "Brood Wars Terran 5 - Town E",
  "Brood Wars Terran 5 - Town F",
  "Brood Wars Terran 6 - Town A",
  "Brood Wars Terran 6 - Town ",
  "Brood Wars Terran 6 - Town C",
  "Brood Wars Terran 6 - Town D",
  "Brood Wars Terran 6 - Town E",
  "Brood Wars Terran 6 - Town F",
  "Brood Wars Terran 7 - Town A",
  "Brood Wars Terran 7 - Town ",
  "Brood Wars Terran 7 - Town C",
  "Brood Wars Terran 7 - Town D",
  "Brood Wars Terran 7 - Town E",
  "Brood Wars Terran 7 - Town F",
  "Brood Wars Terran 8 - Town A",
  "Brood Wars Terran 8 - Town ",
  "Brood Wars Terran 8 - Town C",
  "Brood Wars Terran 8 - Town D",
  "Brood Wars Terran 8 - Town E",
  "Brood Wars Terran 8 - Town F",
  "Brood Wars Zerg 1 - Town A",
  "Brood Wars Zerg 1 - Town ",
  "Brood Wars Zerg 1 - Town C",
  "Brood Wars Zerg 1 - Town D",
  "Brood Wars Zerg 1 - Town E",
  "Brood Wars Zerg 1 - Town F",
  "Brood Wars Zerg 2 - Town A",
  "Brood Wars Zerg 2 - Town ",
  "Brood Wars Zerg 2 - Town C",
  "Brood Wars Zerg 2 - Town D",
  "Brood Wars Zerg 2 - Town E",
  "Brood Wars Zerg 2 - Town F",
  "Brood Wars Zerg 3 - Town A",
  "Brood Wars Zerg 3 - Town ",
  "Brood Wars Zerg 3 - Town C",
  "Brood Wars Zerg 3 - Town D",
  "Brood Wars Zerg 3 - Town E",
  "Brood Wars Zerg 3 - Town F",
  "Brood Wars Zerg 4 - Town A",
  "Brood Wars Zerg 4 - Town ",
  "Brood Wars Zerg 4 - Town C",
  "Brood Wars Zerg 4 - Town D",
  "Brood Wars Zerg 4 - Town E",
  "Brood Wars Zerg 4 - Town F",
  "Brood Wars Zerg 5 - Town A",
  "Brood Wars Zerg 5 - Town ",
  "Brood Wars Zerg 5 - Town C",
  "Brood Wars Zerg 5 - Town D",
  "Brood Wars Zerg 5 - Town E",
  "Brood Wars Zerg 5 - Town F",
  "Brood Wars Zerg 6 - Town A",
  "Brood Wars Zerg 6 - Town ",
  "Brood Wars Zerg 6 - Town C",
  "Brood Wars Zerg 6 - Town D",
  "Brood Wars Zerg 6 - Town E",
  "Brood Wars Zerg 6 - Town F",
  "Brood Wars Zerg 7 - Town A",
  "Brood Wars Zerg 7 - Town ",
  "Brood Wars Zerg 7 - Town C",
  "Brood Wars Zerg 7 - Town D",
  "Brood Wars Zerg 7 - Town E",
  "Brood Wars Zerg 7 - Town F",
  "Brood Wars Zerg 8 - Town A",
  "Brood Wars Zerg 8 - Town ",
  "Brood Wars Zerg 8 - Town C",
  "Brood Wars Zerg 8 - Town D",
  "Brood Wars Zerg 8 - Town E",
  "Brood Wars Zerg 8 - Town F",
  "Brood Wars Zerg 9 - Town A",
  "Brood Wars Zerg 9 - Town ",
  "Brood Wars Zerg 9 - Town C",
  "Brood Wars Zerg 9 - Town D",
  "Brood Wars Zerg 9 - Town E",
  "Brood Wars Zerg 9 - Town F",
  "Brood Wars Zerg 10 - Town A",
  "Brood Wars Zerg 10 - Town ",
  "Brood Wars Zerg 10 - Town C",
  "Brood Wars Zerg 10 - Town D",
  "Brood Wars Zerg 10 - Town E",
  "Brood Wars Zerg 10 - Town F",
];

export const SCTrgUnit = [
  "Terran Marine",
  "Terran Ghost",
  "Terran Vulture",
  "Terran Goliath",
  "Goliath Turret",
  "Terran Siege Tank (Tank Mode)",
  "Tank Turret",
  "Terran SCV",
  "Terran Wraith",
  "Terran Science Vessel",
  "Gui Montag (Firebat)",
  "Terran Dropship",
  "Terran Battlecruiser",
  "Vulture Spider Mine",
  "Nuclear Missile",
  "Terran Civilian",
  "Sarah Kerrigan (Ghost)",
  "Alan Schezar (Goliath)",
  "Alan Turret",
  "Jim Raynor (Vulture)",
  "Jim Raynor (Marine)",
  "Tom Kazansky (Wraith)",
  "Magellan (Science Vessel)",
  "Edmund Duke (Siege Tank)",
  "Duke Turret",
  "Edmund Duke (Siege Mode)",
  "Duke Turret",
  "Arcturus Mengsk (Battlecruiser)",
  "Hyperion (Battlecruiser)",
  "Norad II (Battlecruiser)",
  "Terran Siege Tank (Siege Mode)",
  "Tank Turret",
  "Terran Firebat",
  "Scanner Sweep",
  "Terran Medic",
  "Zerg Larva",
  "Zerg Egg",
  "Zerg Zergling",
  "Zerg Hydralisk",
  "Zerg Ultralisk",
  "Zerg Broodling",
  "Zerg Drone",
  "Zerg Overlord",
  "Zerg Mutalisk",
  "Zerg Guardian",
  "Zerg Queen",
  "Zerg Defiler",
  "Zerg Scourge",
  "Torrasque (Ultralisk)",
  "Matriarch (Queen)",
  "Infested Terran",
  "Infested Kerrigan (Infested Terran)",
  "Unclean One (Defiler)",
  "Hunter Killer (Hydralisk)",
  "Devouring One (Zergling)",
  "Kukulza (Mutalisk)",
  "Kukulza (Guardian)",
  "Yggdrasill (Overlord)",
  "Terran Valkyrie",
  "Cocoon",
  "Protoss Corsair",
  "Protoss Dark Templar",
  "Zerg Devourer",
  "Protoss Dark Archon",
  "Protoss Probe",
  "Protoss Zealot",
  "Protoss Dragoon",
  "Protoss High Templar",
  "Protoss Archon",
  "Protoss Shuttle",
  "Protoss Scout",
  "Protoss Arbiter",
  "Protoss Carrier",
  "Protoss Interceptor",
  "Dark Templar (Hero)",
  "Zeratul (Dark Templar)",
  "Tassadar/Zeratul (Archon)",
  "Fenix (Zealot)",
  "Fenix (Dragoon)",
  "Tassadar (Templar)",
  "Mojo (Scout)",
  "Warbringer (Reaver)",
  "Gantrithor (Carrier)",
  "Protoss Reaver",
  "Protoss Observer",
  "Protoss Scarab",
  "Danimoth (Arbiter)",
  "Aldaris (Templar)",
  "Artanis (Scout)",
  "Rhynadon (Badlands)",
  "Bengalaas (Jungle)",
  "Unused",
  "Unused",
  "Scantid (Desert)",
  "Kakaru (Twilight)",
  "Ragnasaur (Ash World)",
  "Ursadon (Ice World)",
  "Zerg Lurker Egg",
  "Raszagal (Dark Templar)",
  "Samir Duran (Ghost)",
  "Alexei Stukov (Ghost)",
  "Map Revealer",
  "Gerard DuGalle (Ghost)",
  "Zerg Lurker",
  "Infested Duran",
  "Disruption Field",
  "Terran Command Center",
  "Terran Comsat Station",
  "Terran Nuclear Silo",
  "Terran Supply Depot",
  "Terran Refinery",
  "Terran Barracks",
  "Terran Academy",
  "Terran Factory",
  "Terran Starport",
  "Terran Control Tower",
  "Terran Science Facility",
  "Terran Covert Ops",
  "Terran Physics Lab",
  "Unused Terran Bldg",
  "Terran Machine Shop",
  "Unused Terran Bldg",
  "Terran Engineering Bay",
  "Terran Armory",
  "Terran Missile Turret",
  "Terran Bunker",
  "Norad II (Crashed Battlecruiser)",
  "Ion Cannon",
  "Uraj Crystal",
  "Khalis Crystal",
  "Infested Command Center",
  "Zerg Hatchery",
  "Zerg Lair",
  "Zerg Hive",
  "Zerg Nydus Canal",
  "Zerg Hydralisk Den",
  "Zerg Defiler Mound",
  "Zerg Greater Spire",
  "Zerg Queen's Nest",
  "Zerg Evolution Chamber",
  "Zerg Ultralisk Cavern",
  "Zerg Spire",
  "Zerg Spawning Pool",
  "Zerg Creep Colony",
  "Zerg Spore Colony",
  "Unused Zerg Bldg",
  "Zerg Sunken Colony",
  "Zerg Overmind (With Shell)",
  "Zerg Overmind",
  "Zerg Extractor",
  "Mature Crysalis",
  "Zerg Cerebrate",
  "Zerg Cerebrate Daggoth",
  "Unused Zerg Bldg 5",
  "Protoss Nexus",
  "Protoss Robotics Facility",
  "Protoss Pylon",
  "Protoss Assimilator",
  "Protoss Unused",
  "Protoss Observatory",
  "Protoss Gateway",
  "Protoss Unused",
  "Protoss Photon Cannon",
  "Protoss Citadel of Adun",
  "Protoss Cybernetics Core",
  "Protoss Templar Archives",
  "Protoss Forge",
  "Protoss Stargate",
  "Stasis Cell/Prison",
  "Protoss Fleet Beacon",
  "Protoss Arbiter Tribunal",
  "Protoss Robotics Support Bay",
  "Protoss Shield Battery",
  "Khaydarin Crystal Formation",
  "Protoss Temple",
  "Xel'Naga Temple",
  "Mineral Field (Type 1)",
  "Mineral Field (Type 2)",
  "Mineral Field (Type 3)",
  "Cave",
  "Cave-in",
  "Cantina",
  "Mining Platform",
  "Independent Command Center",
  "Independent Starport",
  "Jump Gate",
  "Ruins",
  "Kyadarin Crystal Formation",
  "Vespene Geyser",
  "Warp Gate",
  "Psi Disrupter",
  "Zerg Marker",
  "Terran Marker",
  "Protoss Marker",
  "Zerg Beacon",
  "Terran Beacon",
  "Protoss Beacon",
  "Zerg Flag Beacon",
  "Terran Flag Beacon",
  "Protoss Flag Beacon",
  "Power Generator",
  "Overmind Cocoon",
  "Dark Swarm",
  "Floor Missile Trap",
  "Floor Hatch (UNUSED)",
  "Left Upper Level Door",
  "Right Upper Level Door",
  "Left Pit Door",
  "Right Pit Door",
  "Floor Gun Trap",
  "Left Wall Missile Trap",
  "Left Wall Flame Trap",
  "Right Wall Missile Trap",
  "Right Wall Flame Trap",
  "Start Location",
  "Flag",
  "Young Chrysalis",
  "Psi Emitter",
  "Data Disc",
  "Khaydarin Crystal",
  "Mineral Chunk (Type 1)",
  "Mineral Chunk (Type 2)",
  "Vespene Orb (Protoss Type 1)",
  "Vespene Orb (Protoss Type 2)",
  "Vespene Sac (Zerg Type 1)",
  "Vespene Sac (Zerg Type 2)",
  "Vespene Tank (Terran Type 1)",
  "Vespene Tank (Terran Type 2)",
];
